- type: job
  id: HeadOfSanitation
  name: job-name-janitor-head-of-sanitation
  description: job-description-head-of-sanitation
  playTimeTracker: JobCommandHeadOfSanitation
  setPreference: false
  startingGear: HeadOfSanitationGear
  icon: "JobIconHeadOfSanitation"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Command
  - Janitor
  - Service
  - Maintenance
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: HeadOfSanitationGear
  equipment:
    back: ClothingBackpackSatchelLeather
    ears: ClothingHeadsetCommand
    eyes: ClothingEyesGlassesChemical
    gloves: ClothingHandsGlovesJanitor
    id: HeadofSanitationPDA
    jumpsuit: ClothingUniformJanitorOveralls
    outerClothing: ClothingOuterVestHazard
    shoes: ClothingShoesGaloshes
    head: ClothingHeadHatHardhatYellow
    belt: ClothingBeltJanitorFilled
    pocket1: Flash
  storage:
    back:
    - Flash
    - Crowbar
