- type: entity
  id: CircuitImprinterLawMatrixMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: law matrix imprinter machine board
  components:
  - type: Sprite
    state: science
  - type: MachineBoard
    prototype: CircuitImprinterLawMatrix
    stackRequirements:
      MatterBin: 1
    tagRequirements:
      GlassBeaker:
        amount: 2
        defaultPrototype: Beaker
      SmallAIChip:
        amount: 1
        defaultPrototype: PotatoAIChip
