- type: playTimeTracker
  id: JobNTCFPilot

- type: playTimeTracker
  id: JobNTCFEngineer

- type: playTimeTracker
  id: JobMercenary

- type: playTimeTracker
  id: JobCentralCommandIntern

- type: playTimeTracker
  id: JobCommandHeadOfTomfoolery

- type: playTimeTracker
  id: JobCommandHeadOfSanitation

- type: playTimeTracker
  id: JobCommandCoffeeLogisticsOfficer

- type: playTimeTracker
  id: JobCommandBridgeAssistant
