using Content.Shared._DV.CCVars;
using Content.Shared._Moffstation.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.Options.UI;

[GenerateTypedNameReferences]
public sealed partial class ForkSpecificTab : Control
{
    public ForkSpecificTab()
    {
        RobustXamlLoader.Load(this);

        Control.AddOptionCheckBox(DCCVars.EsScreenshakeDisabled, DisableScreenshakeCheckBox);
        Control.AddOptionPercentSlider(MoffCCVars.MoffScreenShakeIntensity, ScreenShakeIntensitySlider, max: 1.5f);
    }
}
