using Content.Client.Options.UI;
using Content.Shared._DV.CCVars;
using Content.Shared._Moffstation.CCVar;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client._Moffstation.Options.UI;

[GenerateTypedNameReferences]
public sealed partial class ForkSpecificTab : Control
{
    [Dependency] private IConfigurationManager _cfg = default!;

    public ForkSpecificTab()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Control.AddOptionCheckBox(DCCVars.EsScreenshakeDisabled, DisableScreenshakeCheckBox);
        Control.AddOptionPercentSlider(MoffCCVars.MoffScreenShakeIntensity, ScreenShakeIntensitySlider, max: 1.5f);
        Control.AddOption(new OptionParticleQuality(Control, _cfg, DropDownParticleQuality)); // _Starfall: Particle quality.
    }


    // _Starfall Start: Particles
    private sealed class OptionParticleQuality : BaseOption
    {
        private readonly IConfigurationManager _cfg;
        private readonly OptionDropDown _dropDown;

        private const int QualityOff    = 0;
        private const int QualityLow    = 1;
        private const int QualityMedium = 2;
        private const int QualityHigh   = 3;
        private const int QualityDefault = QualityHigh;

        public OptionParticleQuality(OptionsTabControlRow controller, IConfigurationManager cfg, OptionDropDown dropDown) : base(controller)
        {
            _cfg = cfg;
            _dropDown = dropDown;
            var button = dropDown.Button;
            button.AddItem(Loc.GetString("ui-options-particles-off"),    QualityOff);
            button.AddItem(Loc.GetString("ui-options-particles-low"),    QualityLow);
            button.AddItem(Loc.GetString("ui-options-particles-medium"), QualityMedium);
            button.AddItem(Loc.GetString("ui-options-particles-high"),   QualityHigh);
            button.OnItemSelected += args =>
            {
                _dropDown.Button.SelectId(args.Id);
                ValueChanged();
            };
        }

        public override void LoadValue()
        {
            _dropDown.Button.SelectId(_cfg.GetCVar(CCVars.ParticleQuality));
        }

        public override void SaveValue()
        {
            _cfg.SetCVar(CCVars.ParticleQuality, _dropDown.Button.SelectedId);
        }

        public override void ResetToDefault()
        {
            _dropDown.Button.SelectId(QualityDefault);
        }

        public override bool IsModified()
        {
            return _dropDown.Button.SelectedId != _cfg.GetCVar(CCVars.ParticleQuality);
        }

        public override bool IsModifiedFromDefault()
        {
            return _dropDown.Button.SelectedId != QualityDefault;
        }
    }
    // _Starfall End: Particles
}
