using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Moffstation.RespawnButton;

[GenerateTypedNameReferences]
public sealed partial class GhostRespawnRulesWindow : FancyWindow
{
    public event Action? GhostRespawnPressed;

    public GhostRespawnRulesWindow()
    {
        RobustXamlLoader.Load(this);
        ConfirmRespawnButton.OnPressed += _ => Close();
        ConfirmRespawnButton.OnPressed += _ => GhostRespawnPressed?.Invoke();
    }
}
