using System.Linq;
using Content.Shared._Moffstation.MoffPatreon;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._Moffstation.MoffPatreon;

[GenerateTypedNameReferences]
public sealed partial class MoffPatreonWindow : DefaultWindow
{
    public event Action<Guid>? OnRemovePatron;
    public event Action<string>? OnAddOnlineUser;
    public event Action<string>? OnAddById;

    private List<UsernameAndGuid> _patrons = [];

    public MoffPatreonWindow()
    {
        RobustXamlLoader.Load(this);

        AddOnlineButton.OnPressed += _ =>
        {
            if (OnlinePlayerDropdown.SelectedId >= 0)
            {
                var name = (string)OnlinePlayerDropdown.SelectedMetadata!;
                OnAddOnlineUser?.Invoke(name);
            }
        };

        AddIdButton.OnPressed += _ =>
        {
            var text = IdInput.Text.Trim();
            if (!string.IsNullOrEmpty(text))
            {
                OnAddById?.Invoke(text);
                IdInput.Text = "";
            }
        };

        SearchInput.OnTextChanged += _ => RebuildList();
    }

    public void UpdateState(MoffPatreonEuiState state)
    {
        OnlinePlayerDropdown.Clear();

        if (state.OnlinePlayers.Count == 0)
        {
            OnlinePlayerDropdown.AddItem(Loc.GetString("moff-patreon-panel-no-online-players"), -1);
            AddOnlineButton.Disabled = true;
        }
        else
        {
            foreach (var (idx, name) in state.OnlinePlayers.Index())
            {
                OnlinePlayerDropdown.AddItem(name, idx);
                OnlinePlayerDropdown.SetItemMetadata(idx, name);
            }

            AddOnlineButton.Disabled = false;
        }

        _patrons = state.Patrons;
        RebuildList();
    }

    private void RebuildList()
    {
        PatronList.RemoveAllChildren();

        var search = SearchInput.Text.Trim();
        var filtered = string.IsNullOrEmpty(search)
            ? _patrons.AsEnumerable()
            : _patrons.AsEnumerable()
                .Where(it => it.Username.Contains(search, StringComparison.OrdinalIgnoreCase));

        foreach (var (username, guid) in filtered.OrderBy(e => e.Username))
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                VerticalExpand = false,
                Margin = new Thickness(0, 1),
            };

            var nameLabel = new Label
            {
                Text = username,
                HorizontalExpand = true,
                ClipText = true,
                VerticalAlignment = VAlignment.Center
            };

            var removeButton = new TextureButton
            {
                StyleClasses = { StyleClassWindowCloseButton },
                ToolTip = Loc.GetString("moff-patreon-panel-remove-tooltip", ("username", username)),
                HorizontalAlignment = HAlignment.Right,
            };
            removeButton.OnPressed += _ => OnRemovePatron?.Invoke(guid);

            row.AddChild(nameLabel);
            row.AddChild(removeButton);
            PatronList.AddChild(row);
        }

        if (PatronList.ChildCount == 0)
        {
            PatronList.AddChild(new Label
            {
                Text = Loc.GetString("moff-patreon-panel-no-patrons"),
                FontColorOverride = Color.Gray,
            });
        }
    }

    public void ShowAddResponse(int successful, List<string> failed)
    {
        LocId locString;
        if (failed.Count == 0)
        {
            locString = "moff-patreon-panel-add-success-multiple";
        }
        else if (successful == 0)
        {
            locString = "moff-patreon-panel-add-fail-multiple";
        }
        else
        {
            locString = "moff-patreon-panel-add-partial";
        }

        ShowStatus(
            Loc.GetString(
                locString,
                ("numSuccessful", successful),
                ("numFailed", failed.Count),
                ("joinedFailedNames", string.Join(", ", failed))
            ),
            failed.Count == 0
        );
    }

    public void ShowRemoveResponse(bool success)
    {
        ShowStatus(Loc.GetString("moff-patreon-panel-remove-success"), success);
    }

    private void ShowStatus(string text, bool success)
    {
        StatusLabel.Text = text;
        StatusLabel.FontColorOverride = success ? Color.Green : Color.Red;
        StatusLabel.Visible = true;
    }
}
