using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._tc14.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._tc14.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class ResearchTableWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IPrototypeManager _protoMan = default!;
    private readonly SpriteSystem _sprite;

    private EntityUid _entity;
    private ProtoId<ResearchEntryPrototype>? _selectedResearch;

    private Action? _onResearchButtonClicked;
    private Action? _onPrintButtonClicked;

    public ResearchTableWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprite = _entMan.System<SpriteSystem>();
        var a = new Vector2i();

        ResearchItemResearchButton.OnPressed += _ => { _onResearchButtonClicked?.Invoke(); };
        ResearchItemPrintButton.OnPressed += _ => { _onPrintButtonClicked?.Invoke(); };
        _onResearchButtonClicked += ResearchItem;
        _onPrintButtonClicked += PrintBlueprint;

        var prototypes = _protoMan.EnumeratePrototypes<ResearchEntryPrototype>();
        var i = 0;
        foreach (var prototype in prototypes)
        {
            var button = CreateResearchItem(prototype);
            LayoutContainer.SetPosition(button, new Vector2(i,i));
            i += 64;
        }
        UpdateResearchItemSidePanel();
    }

    private void PrintBlueprint()
    {
        throw new NotImplementedException();
    }

    private void ResearchItem()
    {
        throw new NotImplementedException();
    }

    private ResearchTableItem CreateResearchItem(ResearchEntryPrototype prototype)
    {
        var button = new ResearchTableItem(prototype);
        ResearchTreeDragContainer.AddChild(button);
        button.OnButtonClicked += () =>
        {
            UpdateResearchItemSidePanel(button.proto);
        };
        return button;
    }

    private void UpdateResearchItemSidePanel(ProtoId<ResearchEntryPrototype>? researchId = null)
    {
        if (researchId is not null)
            _selectedResearch = researchId;
        if (_selectedResearch is null)
        {
            ResearchItemName.Text = Loc.GetString("research-table-unknownresearch");
            ResearchItemDiscipline.Visible = false;
            ResearchItemPointsNeeded.Visible = false;
            ResearchItemButtons.Visible = false;
            return;
        }
        if (!_protoMan.Resolve(_selectedResearch, out var prototype))
            return;
        if (!_protoMan.Resolve(prototype.Discipline, out var disciplineProto))
            return;
        ResearchItemDiscipline.Visible = true;
        ResearchItemPointsNeeded.Visible = true;
        ResearchItemButtons.Visible = true;
        ResearchItemName.Text = Loc.GetString(prototype.Name);
        ResearchItemDisciplineIcon.Texture = _sprite.Frame0(disciplineProto.Icon);
        ResearchItemDisciplineName.Text = Loc.GetString(disciplineProto.Name);
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        //TODO draw dependency lines using handle.DrawLine
    }

    public void SetEntity(EntityUid uid)
    {
        _entity = uid;
    }
}
