using System.Linq;
using System.Numerics;
using Content.Shared._tc14.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._tc14.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class ResearchTreeContainer : LayoutContainer
{
    public Dictionary<Vector2i, ResearchEntryPrototype> Grid = new();
    public int GridScale;

    public ResearchTreeContainer()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        var itemCenterVector = new Vector2(GridScale, GridScale);
        itemCenterVector /= 3; //half the size of an item; 96/3 = 64/2
        foreach (var dependant in Children.OfType<ResearchTableItem>())
        {
            foreach (var dependencyId in dependant.proto.Dependencies)
            {
                var dependency = GetItemByProtoId(dependencyId);
                handle.DrawLine(dependency.PixelPosition+itemCenterVector, dependant.PixelPosition+itemCenterVector, Color.White);
            }
        }
    }

    private ResearchTableItem GetItemByProtoId(ProtoId<ResearchEntryPrototype> protoId)
    {
        return Children.OfType<ResearchTableItem>().First(i => i.proto.ID == protoId);
    }
}
