using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._tc14.Research;
using Content.Shared._tc14.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._tc14.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class ResearchTableWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IPrototypeManager _protoMan = default!;
    private readonly SpriteSystem _sprite;

    private EntityUid _entity;
    private ProtoId<ResearchEntryPrototype>? _selectedResearch;
    private int _gridScale = 96; // 1.5x size of ResearchTableItem
    private Vector2 _maxPoint = Vector2.One;
    private ResearchTableState _lastState = default!;

    public Action<ProtoId<ResearchEntryPrototype>>? OnResearchButtonClicked;
    public Action<ProtoId<ResearchEntryPrototype>>? OnPrintButtonClicked;

    //TODO this has a lot of LINQ and resolves; really need to cache some stuff
    public ResearchTableWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprite = _entMan.System<SpriteSystem>();

        ResearchTreeDragContainer.GridScale = _gridScale;
        ResearchItemResearchButton.OnPressed += _ => { OnResearchButtonClicked?.Invoke(_selectedResearch ?? ""); };
        ResearchItemPrintButton.OnPressed += _ => { OnPrintButtonClicked?.Invoke(_selectedResearch ?? ""); };
        var prototypes = _protoMan.EnumeratePrototypes<ResearchEntryPrototype>();
        foreach (var prototype in prototypes)
        {
            ResearchTreeDragContainer.Grid.Add(prototype.GridLocation, prototype);
            _maxPoint.X = Math.Max(_maxPoint.X, prototype.GridLocation.X);
            _maxPoint.Y = Math.Max(_maxPoint.Y, prototype.GridLocation.Y);
        }
        _maxPoint += Vector2.One; // off by one :(
        ResearchTreeDragContainer.SetSize = _gridScale * _maxPoint;
        foreach (var pair in ResearchTreeDragContainer.Grid)
        {
            CreateResearchItem(pair.Value);
        }
        FallbackResearchItemSidePanel(); // No state update initially, so...
    }

    private ResearchTableItem CreateResearchItem(ResearchEntryPrototype prototype)
    {
        var button = new ResearchTableItem(prototype);
        ResearchTreeDragContainer.AddChild(button);
        button.OnButtonClicked += () =>
        {
            ChangeResearch(button.proto);
        };
        button.SetEnabled(prototype.Dependencies.Count == 0);
        LayoutContainer.SetPosition(button, GridCoordsToControlCoords(prototype.GridLocation, true));
        return button;
    }

    private Vector2 GridCoordsToControlCoords(Vector2i gridCoords, bool isCenter = false)
    {
        var ret = gridCoords * _gridScale;
        if (isCenter)
            ret += new Vector2i(_gridScale/6, _gridScale/6);
        return ret;
    }

    private void ChangeResearch(ProtoId<ResearchEntryPrototype> researchId)
    {
        _selectedResearch = researchId;
        UpdateResearchItemSidePanel(_lastState.StoredPoints, _lastState.ResearchedTechs);
    }

    private void FallbackResearchItemSidePanel()
    {
        ResearchItemName.Text = Loc.GetString("research-table-unknownresearch");
        ResearchItemDiscipline.Visible = false;
        ResearchItemPointsNeeded.Visible = false;
        ResearchItemButtons.Visible = false;
        ResearchItemUnlockedItems.Visible = false;
    }

    private void UpdateResearchItemSidePanel(Dictionary<ProtoId<ResearchDisciplinePrototype>, int> storedPoints, HashSet<ProtoId<ResearchEntryPrototype>> researched)
    {
        if (_selectedResearch is null)
        {
            FallbackResearchItemSidePanel();
            return;
        }
        if (!_protoMan.Resolve(_selectedResearch, out var prototype))
            return;
        if (!_protoMan.Resolve(prototype.Discipline, out var disciplineProto))
            return;
        ResearchItemUnlockedItems.RemoveAllChildren();
        foreach (var latheRecipeId in prototype.UnlockedRecipes)
        {
            if (!_protoMan.Resolve(latheRecipeId, out var latheRecipe) || latheRecipe.Result is null || !_protoMan.Resolve(latheRecipe.Result, out var outputItem))
                continue;
            var previewBox = new BoxContainer();
            previewBox.Orientation = BoxContainer.LayoutOrientation.Horizontal;
            previewBox.SeparationOverride = 5;
            var previewItem = new EntityPrototypeView();
            previewItem.SetPrototype(latheRecipe.Result);
            var previewLabel = new Label();
            previewLabel.Text = outputItem.Name;
            previewBox.AddChild(previewItem);
            previewBox.AddChild(previewLabel);
            ResearchItemUnlockedItems.AddChild(previewBox);
        }
        ResearchItemUnlockedItems.Visible = true;
        ResearchItemDiscipline.Visible = true;
        ResearchItemPointsNeeded.Visible = true;
        ResearchItemButtons.Visible = true;
        ResearchItemPointsNeeded.Text = Loc.GetString("research-table-pointsneeded",
            ("currentPoints", storedPoints[disciplineProto.ID]),
            ("neededPoints", prototype.Points)
        );
        ResearchItemResearchButton.Disabled = storedPoints[disciplineProto.ID] < prototype.Points || researched.Contains(prototype.ID);
        ResearchItemPrintButton.Disabled = !researched.Contains(prototype.ID);
        ResearchItemName.Text = Loc.GetString(prototype.Name);
        ResearchItemDisciplineIcon.Texture = _sprite.Frame0(disciplineProto.Icon);
        ResearchItemDisciplineName.Text = Loc.GetString(disciplineProto.Name);
    }

    private void UpdatePoints(Dictionary<ProtoId<ResearchDisciplinePrototype>, int> storedPoints)
    {
        ResearchTablePointsDisplay.RemoveAllChildren();
        foreach (var pair in storedPoints)
        {
            if (!_protoMan.Resolve(pair.Key, out var proto))
                continue;
            var box = new BoxContainer();
            box.SeparationOverride = 5;
            var icon = new TextureRect();
            icon.Texture = _sprite.Frame0(proto.Icon);
            icon.TextureScale = new Vector2(2, 2);
            icon.VerticalAlignment = VAlignment.Center;
            var label = new Label();
            label.Text = pair.Value.ToString();
            box.AddChild(icon);
            box.AddChild(label);
            ResearchTablePointsDisplay.AddChild(box);
        }
    }

    private void UpdateResearchItems(HashSet<ProtoId<ResearchEntryPrototype>> researched)
    {
        foreach (var child in ResearchTreeDragContainer.Children.OfType<ResearchTableItem>())
        {
            child.SetResearched(researched.Contains(child.proto));
            if (child.proto.Dependencies.Count == 0)
            {
                child.SetEnabled(true);
                continue;
            }

            child.SetEnabled(child.proto.Dependencies.All(researched.Contains));
        }
    }

    public void UpdateState(ResearchTableState state)
    {
        UpdateResearchItems(state.ResearchedTechs);
        UpdatePoints(state.StoredPoints);
        UpdateResearchItemSidePanel(state.StoredPoints, state.ResearchedTechs);
        _lastState = state;
    }

    public void SetEntity(EntityUid uid)
    {
        _entity = uid;
    }
}
