using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._tc14.Research.Components;
using Content.Shared._tc14.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._tc14.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class ResearchTableWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IPrototypeManager _protoMan = default!;
    private readonly SpriteSystem _sprite;

    private EntityUid _entity;
    private ProtoId<ResearchEntryPrototype>? _selectedResearch;
    private Dictionary<Vector2i, ProtoId<ResearchEntryPrototype>> _grid = new();
    private int _gridScale = 96; // 1.5x size of ResearchTableItem

    private Action? _onResearchButtonClicked;
    private Action? _onPrintButtonClicked;

    public ResearchTableWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprite = _entMan.System<SpriteSystem>();

        ResearchTreeRecenterButton.OnPressed += RecenterTree;
        ResearchItemResearchButton.OnPressed += _ => { _onResearchButtonClicked?.Invoke(); };
        ResearchItemPrintButton.OnPressed += _ => { _onPrintButtonClicked?.Invoke(); };
        _onResearchButtonClicked += ResearchItem;
        _onPrintButtonClicked += PrintBlueprint;

        // Fill research tree
        var prototypes = _protoMan.EnumeratePrototypes<ResearchEntryPrototype>();
        foreach (var prototype in prototypes)
        {
            var button = CreateResearchItem(prototype);
        }
        UpdateResearchItemSidePanel();
        UpdatePoints();
    }

    private void PrintBlueprint()
    {
        throw new NotImplementedException();
    }

    private void ResearchItem()
    {
        throw new NotImplementedException();
    }

    private void RecenterTree(BaseButton.ButtonEventArgs buttonEventArgs)
    {
        // ReSharper disable once PossibleLossOfFraction
        ResearchTreeScrollContainer.SetScrollValue(ResearchTreeDragContainer.SetSize/4 + Vector2.One*(_gridScale/2)); // I have no idea why, I have no idea how, but SetSize/2 is NOT the control's center. WHY IS THIS HAPPENING
    }

    private ResearchTableItem CreateResearchItem(ResearchEntryPrototype prototype)
    {
        var button = new ResearchTableItem(prototype);
        ResearchTreeDragContainer.AddChild(button);
        button.OnButtonClicked += () =>
        {
            UpdateResearchItemSidePanel(button.proto);
        };
        _grid.Add(prototype.GridLocation, prototype.ID);
        LayoutContainer.SetPosition(button, GridCoordsToControlCoords(prototype.GridLocation));
        return button;
    }

    private Vector2 GridCoordsToControlCoords(Vector2i gridCoords)
    {
        return ResearchTreeDragContainer.SetSize/2+ gridCoords * _gridScale;
    }

    private void UpdateResearchItemSidePanel(ProtoId<ResearchEntryPrototype>? researchId = null)
    {
        if (researchId is not null)
            _selectedResearch = researchId;
        if (_selectedResearch is null)
        {
            ResearchItemName.Text = Loc.GetString("research-table-unknownresearch");
            ResearchItemDiscipline.Visible = false;
            ResearchItemPointsNeeded.Visible = false;
            ResearchItemButtons.Visible = false;
            return;
        }
        if (!_protoMan.Resolve(_selectedResearch, out var prototype))
            return;
        if (!_protoMan.Resolve(prototype.Discipline, out var disciplineProto))
            return;
        ResearchItemDiscipline.Visible = true;
        ResearchItemPointsNeeded.Visible = true;
        ResearchItemButtons.Visible = true;
        ResearchItemName.Text = Loc.GetString(prototype.Name);
        ResearchItemDisciplineIcon.Texture = _sprite.Frame0(disciplineProto.Icon);
        ResearchItemDisciplineName.Text = Loc.GetString(disciplineProto.Name);
    }

    private void UpdatePoints()
    {
        if (!_entMan.TryGetComponent<ResearchTableComponent>(_entity, out var comp))
            return;
        foreach (var child in ResearchTablePointsDisplay.Children.OfType<BoxContainer>())
        {
            ResearchTablePointsDisplay.RemoveChild(child);
        }
        foreach (var pair in comp.StoredPoints)
        {
            if (!_protoMan.Resolve(pair.Key, out var proto))
                continue;
            var box = new BoxContainer();
            box.SeparationOverride = 5;
            var icon = new TextureRect();
            icon.Texture = _sprite.Frame0(proto.Icon);
            icon.TextureScale = new Vector2(2, 2);
            icon.VerticalAlignment = VAlignment.Center;
            var label = new Label();
            label.Text = pair.Value.ToString();
            box.AddChild(icon);
            box.AddChild(label);
            ResearchTablePointsDisplay.AddChild(box);
        }
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        //TODO draw dependency lines using handle.DrawLine
    }

    public void SetEntity(EntityUid uid)
    {
        _entity = uid;
        UpdateResearchItemSidePanel();
        UpdatePoints();
    }
}
