using Content.Shared._tc14.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._tc14.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class ResearchTableItem : Control
{
    [Dependency] private readonly IPrototypeManager _protoMan = default!;

    private ResearchEntryPrototype _proto = default!;

    public ResearchTableItem(ResearchEntryPrototype proto)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _proto = proto;
        ResearchItemEntView.SetPrototype("FoodBurgerBacon");
        if (!_protoMan.Resolve(_proto.Discipline, out var discipline))
            return;
        ResearchItemBorder.ModulateSelfOverride = discipline.Color;
    }

    public void SetDisabled(bool disable)
    {
        ResearchItemButton.Disabled = disable;
    }
}
