using Content.Shared._tc14.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._tc14.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class ResearchTableItem : Control
{
    [Dependency] private readonly IPrototypeManager _protoMan = default!;

    public ResearchEntryPrototype proto = default!;
    private ResearchDisciplinePrototype _disciplineProto = default!;

    public Action? OnButtonClicked = default!;

    public ResearchTableItem(ResearchEntryPrototype proto)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        this.proto = proto;
        ResearchItemButton.OnPressed += _ => OnButtonClicked?.Invoke();
        ResearchItemEntView.SetPrototype(this.proto.IconPrototype);
        if (!_protoMan.Resolve(this.proto.Discipline, out var discipline))
            return;
        _disciplineProto = discipline;
        ResearchItemBorder.ModulateSelfOverride = _disciplineProto.Color;
    }

    public void SetEnabled(bool value)
    {
        ResearchItemButton.Disabled = !value;
    }

    public void SetResearched(bool value)
    {
        ResearchItemCheckmark.Visible = value;
    }
}
