using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.LateJoin;

/// <summary>
/// Two column late join layout: a character picker on the left, the upstream job list on the right.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MoffLateJoinLayout : BoxContainer
{
    public MoffLateJoinLayout()
    {
        RobustXamlLoader.Load(this);
    }
}
