using Content.Client.UserInterface.Controls;
using Content.Shared._DV.CustomObjectiveSummary; // Moffstation - Objective Selection
using Content.Shared.Mind;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._DV.CustomObjectiveSummary;

[GenerateTypedNameReferences]
public sealed partial class CustomObjectiveSummaryWindow : FancyWindow
{
    [Dependency] private readonly IPlayerManager _players = default!;
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IGameTiming _gameTiming = default!;

    private SharedMindSystem? _mind;

    private readonly int _maxLength = 512;

    private TimeSpan _nextTextUpdate = TimeSpan.Zero;

    public event Action<string>? OnSubmitted;
    public event Action<string>? UpdateText;

    public CustomObjectiveSummaryWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SubmitButton.OnPressed +=
            _ => OnSubmitted?.Invoke(Rope.Collapse(ObjectiveSummaryTextEdit.TextRope));
        ObjectiveSummaryTextEdit.OnTextChanged += _ =>
        {
            UpdateWordCount();
            if (ObjectiveSummaryTextEdit.TextLength > _maxLength || _gameTiming.CurTime < _nextTextUpdate)
                return;
            UpdateText?.Invoke(Rope.Collapse(ObjectiveSummaryTextEdit.TextRope));
            _nextTextUpdate = _gameTiming.CurTime + TimeSpan.FromSeconds(5);
        };

        _mind ??= _entity.System<SharedMindSystem>();

        _mind.TryGetMind(_players.LocalSession, out var mindUid, out _);

        UpdateWordCount();

        if (_entity.TryGetComponent<CustomObjectiveSummaryComponent>(mindUid, out var summary)) // Moffstation -  Objective Selection
            ObjectiveSummaryTextEdit.TextRope = new Rope.Leaf(summary.ObjectiveSummary);

        UpdateWordCount();
    }

    private void UpdateWordCount()
    {
        // Disable the button if its over the max length.
        SubmitButton.Disabled = ObjectiveSummaryTextEdit.TextLength > _maxLength;
        CharacterLimitLabel.FontColorOverride = ObjectiveSummaryTextEdit.TextLength > _maxLength ? Color.Red : null;
        CharacterLimitLabel.Text = ObjectiveSummaryTextEdit.TextLength + "/" + _maxLength;
    }
}
