using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.DiegeticUI;

[GenerateTypedNameReferences]
public sealed partial class MoffDiegeticButtonPhysical : ContainerButton
{
    private const float PressedDarken = 0.7f;

    public event Action? OnKeyPressed;

    [Dependency] private IResourceCache _resourceCache = null!;

    private Color _baseColor = Color.White;
    private Color _hoverColor = new(1.2f, 1.2f, 1.2f);
    private Color _pressedColor = new(PressedDarken, PressedDarken, PressedDarken);
    private readonly VectorFont _fontOverride;

    private readonly StyleBoxTexture _keyBox;
    private readonly bool _controlsReady;

    [ViewVariables]
    public string? Text { get => KeyLabel.Text; set => KeyLabel.Text = value; }

    [ViewVariables]
    public Color Color
    {
        get => _baseColor;
        set => SetTint(value);
    }

    [ViewVariables]
    public Color FontColor
    {
        set => KeyLabel.FontColorOverride = value;
    }

    public MoffDiegeticButtonPhysical()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _keyBox = (StyleBoxTexture) StyleBoxOverride!;

        _controlsReady = true;

        _fontOverride ??= new VectorFont(_resourceCache.GetResource<FontResource>("/Fonts/Sysfont/Sysfont-Regular.otf"), 14);
        KeyLabel.FontOverride = _fontOverride;

        OnPressed += _ => OnKeyPressed?.Invoke();

        DrawModeChanged();
    }

    private void SetTint(Color color)
    {
        _baseColor = color;
        const float hoverMultiplier = 1.1f;
        const float pressedMultiplier = 0.7f;
        _hoverColor = new Color(color.R * hoverMultiplier, color.G * hoverMultiplier, color.B * hoverMultiplier);
        _pressedColor = new Color(color.R * pressedMultiplier, color.G * pressedMultiplier, color.B * pressedMultiplier);
        DrawModeChanged();
    }

    protected override void DrawModeChanged()
    {
        base.DrawModeChanged();

        if (!_controlsReady)
            return;

        _keyBox.Modulate = DrawMode switch
        {
            DrawModeEnum.Pressed => _pressedColor,
            DrawModeEnum.Hover => _hoverColor,
            _ => _baseColor,
        };
    }
}
