using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.DeltaV.QuickPhrase;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.DeltaV.AACTablet.UI;

[GenerateTypedNameReferences]
public sealed partial class AACWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    public event Action<ProtoId<QuickPhrasePrototype>>? PhraseButtonPressed;

    public AACWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        var phrases = GetPhrasesByTabAndGroup();
        foreach (var (idx, tab) in phrases.Index())
        {
            var (tabName, phrasesByGroup) = tab;
            var tabC = new ScrollContainer { VerticalExpand = true };
            var boxContainer = CreateBoxContainerForTab(phrasesByGroup);
            tabC.AddChild(boxContainer);
            Content.AddChild(tabC);
            Content.SetTabTitle(idx, tabName);
        }
    }

    private Dictionary<string, Dictionary<string, List<QuickPhrasePrototype>>> GetPhrasesByTabAndGroup() =>
        _prototypeManager.EnumeratePrototypes<QuickPhrasePrototype>()
            .ToList()
            .GroupBy(p => Loc.GetString(p.Tab))
            .OrderBy(tabGroup => tabGroup.Key)
            .ToDictionary(
                tabGroup => tabGroup.Key,
                tabGroup => tabGroup.GroupBy(p => Loc.GetString(p.Group))
                    .OrderBy(groupGroup => groupGroup.Key)
                    .ToDictionary(
                        groupGroup => groupGroup.Key,
                        groupGroup => groupGroup.OrderBy(p => p.LocalizedText).ToList()
                    )
            );

    private BoxContainer CreateBoxContainerForTab(Dictionary<string, List<QuickPhrasePrototype>> groups)
    {
        var boxContainer = new BoxContainer
        {
            HorizontalExpand = true,
            VerticalExpand = true,
            Orientation = BoxContainer.LayoutOrientation.Vertical,
        };

        foreach (var group in groups)
        {
            var buttonContainer = CreateButtonContainerForGroup(group.Value);
            boxContainer.AddChild(new Label { Text = group.Key, Margin = new Thickness(4.0f)});
            boxContainer.AddChild(buttonContainer);
        }

        return boxContainer;
    }

    private GridContainer CreateButtonContainerForGroup(List<QuickPhrasePrototype> phrases)
    {
        var buttonContainer = CreateButtonContainer();
        foreach (var phrase in phrases)
        {
            var text = phrase.LocalizedText;
            var button = CreatePhraseButton(text, phrase.StyleClass);
            button.OnPressed += _ => PhraseButtonPressed?.Invoke(phrase.ID);
            buttonContainer.AddChild(button);
        }

        return buttonContainer;
    }

    private static GridContainer CreateButtonContainer()
    {
        var buttonContainer = new GridContainer
        {
            Margin = new Thickness(10),
            Columns = 4,
        };

        return buttonContainer;
    }

    private static Button CreatePhraseButton(string text, string styleClass)
    {
        var buttonWidth = GetButtonWidth();
        var phraseButton = new Button
        {
            Access = AccessLevel.Public,
            MaxSize = new Vector2(buttonWidth, buttonWidth),
            ClipText = false,
            HorizontalExpand = true,
            StyleClasses = { styleClass },
        };

        var buttonLabel = new RichTextLabel
        {
            Margin = new Thickness(0, 5),
            StyleClasses = { "WhiteText" },
        };

        buttonLabel.SetMessage(text);
        phraseButton.AddChild(buttonLabel);
        return phraseButton;
    }

    private static int GetButtonWidth()
    {
        const int spaceWidth = 10;
        const int parentWidth = 540;
        const int columnCount = 4;

        const int paddingSize = spaceWidth * 2;
        const int gutterScale = (columnCount - 1) / columnCount;
        const int columnWidth = (parentWidth - paddingSize) / columnCount;
        const int buttonWidth = columnWidth - spaceWidth * gutterScale;
        return buttonWidth;
    }
}
