blank_issues_enabled: false
contact_links:
  - name: Report a Security Vulnerability
    url: https://github.com/spess14/trailblazer-colony-14/blob/master/SECURITY.md
    about: Please report security vulnerabilities privately to  so we can fix them before they are publicly disclosed.
