using System.Numerics;
using Content.Shared.Labels.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._Funkystation.VendingMachines.UI;

[GenerateTypedNameReferences]
public sealed partial class VendingMachineGridSlot : PanelContainer
{
    [Dependency] private IPrototypeManager _protoManager = default!;
    [Dependency] private ILocalizationManager _loc = default!;
    [Dependency] private IComponentFactory _compFactory = default!;

    private const float SlotSize = 84f;
    private const float ItemSize = 64f;
    private const float BadgeSize = 20f;
    private const float AnimDuration = 0.55f;
    private const float DropDistance = 20f;
    private const float IconScale = 2.5f;
    private readonly Vector2 _restingPos;
    private bool _animating;
    private float _animElapsed;
    private bool _pendingSoldOut;
    private bool _rowMatch;
    private bool _exactMatch;
    private bool _searchMatch;

    // highlighting
    private static readonly StyleBoxFlat NormalStyle = new() { BackgroundColor = new Color(30, 30, 40), BorderColor = new Color(90, 90, 105), BorderThickness = new Thickness(1) };
    private static readonly StyleBoxFlat RowMatchStyle = new() { BackgroundColor = new Color(40, 50, 70), BorderColor = new Color(120, 140, 190), BorderThickness = new Thickness(2) };
    private static readonly StyleBoxFlat ExactMatchStyle = new() { BackgroundColor = new Color(40, 70, 40), BorderColor = new Color(100, 255, 100), BorderThickness = new Thickness(2) };

    // modulating the slot itself cascades to every child, so it composes with the sold-out sprite dim
    private static readonly Color SearchDimModulate = Color.White.WithAlpha(0.4f);

    public bool SoldOut { get; private set; }

    // what the search bar matches against
    public string ItemName { get; private set; } = string.Empty;

    public VendingMachineGridSlot()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        MouseFilter = MouseFilterMode.Stop;

        MinSize = SetSize = new Vector2(SlotSize, SlotSize);

        PanelOverride = NormalStyle;

        SlotLayout.SetSize = new Vector2(SlotSize, SlotSize);
        LayoutContainer.SetPosition(SlotLayout, Vector2.Zero);

        _restingPos = new Vector2((SlotSize - ItemSize) / 2f, (SlotSize - ItemSize) / 2f);
        ItemSprite.SetSize = new Vector2(ItemSize, ItemSize);
        ItemSprite.Scale = new Vector2(IconScale, IconScale);
        LayoutContainer.SetPosition(ItemSprite, _restingPos);

        LayoutContainer.SetPosition(CodeLabel, new Vector2(2f, 2f));

        AmountBadge.SetSize = new Vector2(BadgeSize, BadgeSize);
        LayoutContainer.SetPosition(AmountBadge, new Vector2(SlotSize - BadgeSize - 2f, SlotSize - BadgeSize - 2f));

        SoldOverlay.SetSize = new Vector2(SlotSize, 22f);
        LayoutContainer.SetPosition(SoldOverlay, new Vector2(0f, (SlotSize - 22f) / 2f));
    }

    public void SetItem(EntProtoId protoId, string code, uint amount, bool soldOut)
    {
        CodeLabel.Text = code;
        ItemSprite.SetPrototype(protoId);
        ItemName = protoId.Id;

        if (_protoManager.TryIndex(protoId, out var proto))
        {
            var tooltipText = proto.Name;

            if (proto.TryComp<LabelComponent>(out var label, _compFactory) && label.LocalizedLabel is { } locId)
            {
                tooltipText = _loc.GetString("comp-label-format",
                    ("baseName", proto.Name),
                    ("label", _loc.GetString(locId)));
            }

            ItemName = tooltipText;

            ToolTip = string.IsNullOrWhiteSpace(proto.Description)
                ? tooltipText
                : $"{tooltipText}\n{proto.Description}";
        }

        SetAmount(amount, soldOut);
    }

    public void SetAmount(uint amount, bool soldOut)
    {
        AmountLabel.Text = amount.ToString();
        SoldOut = soldOut;

        if (_animating)
        {
            _pendingSoldOut = soldOut;
            return;
        }

        ApplySoldOutState(soldOut);
    }

    public void SetSearchDimmed(bool dimmed)
    {
        Modulate = dimmed ? SearchDimModulate : Color.White;
    }

    public void SetSearchHighlight(bool matched)
    {
        _searchMatch = matched;
        UpdatePanel();
    }

    public void SetHighlight(bool isRowMatch, bool isExactMatch)
    {
        _rowMatch = isRowMatch;
        _exactMatch = isExactMatch;
        UpdatePanel();
    }

    // keypad state outranks the search, since those are the imminent vend
    private void UpdatePanel()
    {
        if (_exactMatch)
            PanelOverride = ExactMatchStyle;
        else if (_rowMatch || _searchMatch)
            PanelOverride = RowMatchStyle;
        else
            PanelOverride = NormalStyle;
    }

    private void ApplySoldOutState(bool soldOut)
    {
        SoldOverlay.Visible = soldOut;
        ItemSprite.Modulate = soldOut ? Color.White.WithAlpha(0.3f) : Color.White;
        AmountBadge.Visible = !soldOut;
    }

    public void PlayVendAnimation()
    {
        _animating = true;
        _animElapsed = 0f;
        _pendingSoldOut = SoldOut;

        ResetSprite();
    }

    private void ResetSprite()
    {
        ItemSprite.Modulate = Color.White;
        LayoutContainer.SetPosition(ItemSprite, _restingPos);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_animating)
            return;

        _animElapsed += args.DeltaSeconds;
        var t = Math.Clamp(_animElapsed / AnimDuration, 0f, 1f);

        var pos = _restingPos + new Vector2(0f, DropDistance * t);
        LayoutContainer.SetPosition(ItemSprite, pos);
        ItemSprite.Modulate = Color.White.WithAlpha(1f - t);

        if (t >= 1f)
        {
            _animating = false;
            ResetSprite();
            ApplySoldOutState(_pendingSoldOut);
        }
    }
}
