using System.Collections.Immutable;
using System.Linq;
using System.Numerics;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Moffstation.Lobby.UI;

/// <summary>
/// A drop target for <see cref="DraggableJobIcon"/>, representing one job priority. Handles hover
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class DraggableJobTarget : Control
{
    private static readonly List<JobPrototype> OrderedJobsInternal = new();

    /// <summary>The sort order icons are kept in, shared by every target.</summary>
    public static ImmutableList<JobPrototype> OrderedJobs => OrderedJobsInternal.ToImmutableList();

    /// <summary>Either <see cref="IconGrid"/> or, when high priority, <see cref="HighBox"/>.</summary>
    private Container _jobIconContainer;

    /// <summary>Where the occupant goes when a new icon is dropped on the single high slot.</summary>
    private DraggableJobTarget? _fallbackTarget;

    private JobPriority _priority;

    /// <summary>Which of the two icon containers is shown, and how the target is labelled.</summary>
    public JobPriority Priority
    {
        get => _priority;
        set
        {
            _priority = value;

            PriorityLabel.Text =
                Loc.GetString($"humanoid-profile-editor-job-priority-{value.ToString().ToLower()}-button");

            IconGrid.Visible = !IsHighPriority;
            HighBox.Visible = IsHighPriority;
            _jobIconContainer = IsHighPriority ? HighBox : IconGrid;
        }
    }

    private bool IsHighPriority => Priority == JobPriority.High;

    public DraggableJobTarget()
    {
        RobustXamlLoader.Load(this);

        _jobIconContainer = IconGrid;
        // JobPriority.Never is the default, but the label still has to be filled in.
        Priority = JobPriority.Never;
    }

    /// <summary>
    /// Sets where this target bumps its occupant to. Only meaningful on the high priority target.
    /// </summary>
    public void SetFallbackTarget(DraggableJobTarget target)
    {
        if (!IsHighPriority)
            throw new InvalidOperationException("Only the high priority job target can have a fallback set");

        if (target.IsHighPriority)
            throw new InvalidOperationException("The fallback target must not also be high priority");

        _fallbackTarget = target;
    }

    public void ClearIcons()
    {
        _jobIconContainer.DisposeAllChildren();
    }

    public void RegisterJobIcon(DraggableJobIcon icon)
    {
        icon.OnMouseMove += pos => HandleMouseMove(pos, icon);
        icon.OnMouseUp += pos => HandleMouseUp(pos, icon);
    }

    /// <summary>
    /// Reparents <paramref name="icon"/> into this target. Pass <paramref name="preOrdered"/> when
    /// filling an empty target in order, to skip the insert search.
    /// </summary>
    public void AddJobIcon(DraggableJobIcon icon, bool preOrdered = false)
    {
        if (IsHighPriority && _jobIconContainer.ChildCount > 0)
        {
            if (_fallbackTarget is null)
                return;

            if (_jobIconContainer.Children.First() is not DraggableJobIcon toBump)
                return;

            _fallbackTarget.AddJobIcon(toBump);
        }

        icon.SetScale(Priority);

        // Orphan first: dropping an icon back into the container it already occupies would otherwise
        // shift every later sibling down one after removal, landing the icon a position too late.
        icon.Orphan();

        var insertIndex = preOrdered ? -1 : FindInsertLocation(icon);

        _jobIconContainer.AddChild(icon);

        if (insertIndex >= 0)
            icon.SetPositionInParent(insertIndex);
    }

    private int FindInsertLocation(DraggableJobIcon icon)
    {
        if (IsHighPriority)
            return -1;

        var thisIndex = OrderedJobs.IndexOf(icon.JobProto);

        // FindIndex already returns -1 when every icon present sorts before this one.
        return _jobIconContainer.Children.Cast<DraggableJobIcon>()
            .ToImmutableList()
            .FindIndex(curIcon => OrderedJobs.IndexOf(curIcon.JobProto) > thisIndex);
    }

    private void HandleMouseUp(Vector2 pos, DraggableJobIcon icon)
    {
        if (!icon.Dragging || !GlobalRect.Contains(pos))
            return;

        AddJobIcon(icon);
        BackgroundPanel.Visible = false;
    }

    private void HandleMouseMove(Vector2 pos, DraggableJobIcon icon)
    {
        var contained = GlobalRect.Contains(pos);

        BackgroundPanel.Visible = contained;

        if (contained)
            icon.SetScale(Priority);
    }

    /// <summary>Rebuilds the shared sort order. Call when job or department prototypes change.</summary>
    public static void UpdatedOrderedJobs(IPrototypeManager protoMan)
    {
        OrderedJobsInternal.Clear();

        var departments = protoMan.EnumeratePrototypes<DepartmentPrototype>().ToList();
        departments.Sort(DepartmentUIComparer.Instance);

        foreach (var department in departments)
        {
            var jobs = department.Roles.Select(protoMan.Index).Where(role => role.SetPreference).ToList();
            jobs.Sort(JobUIComparer.Instance);

            foreach (var job in jobs)
            {
                if (!OrderedJobsInternal.Contains(job))
                    OrderedJobsInternal.Add(job);
            }
        }
    }

    public IEnumerable<JobPrototype> GetContainedJobs()
    {
        return _jobIconContainer.Children.Cast<DraggableJobIcon>().Select(icon => icon.JobProto);
    }

    public int ContainedJobCount()
    {
        return _jobIconContainer.ChildCount;
    }

    public void SetColumns(int columns)
    {
        // Clamping to the child count keeps the icons centred, and GridContainer throws on zero.
        if (_jobIconContainer is GridContainer grid)
            grid.Columns = grid.ChildCount == 0 ? 1 : Math.Min(columns, grid.ChildCount);
    }
}
