using System.Linq;
using System.Numerics;
using Content.Client._Moffstation.Preferences;
using Content.Client._Moffstation.ReadyManifest;
using Content.Client.Lobby.UI.Roles;
using Content.Client.Players.PlayTimeTracking;
using Content.Shared._Moffstation.Extensions;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Moffstation.Lobby.UI;

/// <summary>
/// Editor for job priorities, which apply across all of the player's characters. Which jobs a
/// character will take is chosen per character in the roles tab. Adapted from upstream PR #36493.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MoffJobPriorityEditor : BoxContainer
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private JobRequirementsManager _requirements = default!;
    [Dependency] private MoffCharacterSelectionManager _selection = default!;

    private readonly SpriteSystem _sprite;

    // A job can appear in several departments, so entries are not unique by job id.
    private readonly List<(ProtoId<JobPrototype> Job, RequirementsSelector Selector)> _selectors = new();

    private readonly Dictionary<string, MoffJobPriorityDepartment> _departments = new();

    /// <summary>Jobs the player cannot currently take, so a stale priority on them is dropped.</summary>
    private readonly HashSet<ProtoId<JobPrototype>> _locked = new();

    /// <summary>The priorities being edited, not yet pushed to the server.</summary>
    public Dictionary<ProtoId<JobPrototype>, JobPriority> SelectedJobPriorities { get; private set; } = new();

    public MoffJobPriorityEditor()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entManager.System<SpriteSystem>();

        ExplanationLabel.SetMessage(Loc.GetString("moff-job-priority-window-explanation"));

        ResetButton.OnPressed += _ => LoadJobPriorities();

        SaveButton.OnPressed += _ =>
        {
            _selection.UpdateJobPriorities(SelectedJobPriorities);
            LoadJobPriorities();
        };

        RefreshJobs();

        _selection.OnStateChanged += OnStateChanged;
    }

    /// <summary>Discards any unsaved edits and reloads from the player's saved priorities.</summary>
    public void LoadJobPriorities()
    {
        SelectedJobPriorities = new Dictionary<ProtoId<JobPrototype>, JobPriority>(_selection.State.JobPriorities);

        // A job the player has since lost access to stays saved server-side but must not show here,
        // which leaves the editor dirty so they can save the correction.
        foreach (var job in _locked)
        {
            SelectedJobPriorities.Remove(job);
        }

        UpdateSelectors();
        CheckDirty();
    }

    public void RefreshJobs()
    {
        JobList.RemoveAllChildren();
        _departments.Clear();
        _selectors.Clear();
        _locked.Clear();

        // RadioOptions ids are auto-incremented; these only work because they match JobPriority 0-3.
        var items = new[]
        {
            ("humanoid-profile-editor-job-priority-never-button", (int)JobPriority.Never),
            ("humanoid-profile-editor-job-priority-low-button", (int)JobPriority.Low),
            ("humanoid-profile-editor-job-priority-medium-button", (int)JobPriority.Medium),
            ("humanoid-profile-editor-job-priority-high-button", (int)JobPriority.High),
        };

        var departments = _prototypeManager.EnumeratePrototypes<DepartmentPrototype>()
            .Where(department => !department.EditorHidden)
            .ToList();

        departments.Sort(DepartmentUIComparer.Instance);

        var first = true;

        foreach (var department in departments)
        {
            var category = GetOrCreateCategory(department, ref first);

            var jobs = department.Roles
                .Select(jobId => _prototypeManager.Index(jobId))
                .Where(job => job.SetPreference)
                .SortForUi(_prototypeManager)
                .ToList();

            foreach (var job in jobs)
            {
                category.Jobs.AddChild(CreateSelector(job, items));
            }
        }

        LoadJobPriorities();
    }

    private MoffJobPriorityDepartment GetOrCreateCategory(DepartmentPrototype department, ref bool first)
    {
        if (_departments.TryGetValue(department.ID, out var existing))
            return existing;

        var category = new MoffJobPriorityDepartment(department, first);
        first = false;

        _departments[department.ID] = category;
        JobList.AddChild(category);

        return category;
    }

    private RequirementsSelector CreateSelector(JobPrototype job, (string, int)[] items)
    {
        var selector = new RequirementsSelector
        {
            Margin = new Thickness(3f, 3f, 3f, 0f),
        };

        var icon = new TextureRect
        {
            TextureScale = new Vector2(2, 2),
            VerticalAlignment = Control.VAlignment.Center,
        };

        var jobIcon = _prototypeManager.Index(job.Icon);
        icon.Texture = _sprite.Frame0(jobIcon.Icon);

        selector.Setup(items, job.LocalizedName, 200, job.LocalizedDescription, icon, job.Guides);

        // Player-global, so there is no character to check age or species against.
        if (!_requirements.IsAllowed(job, null, out var reason))
        {
            selector.LockRequirements(reason);
            _locked.Add(job.ID);
        }
        else
        {
            selector.UnlockRequirements();
        }

        selector.OnSelected += selected => OnJobSelected(job.ID, (JobPriority)selected);

        _selectors.Add((job.ID, selector));

        return selector;
    }

    private void OnJobSelected(ProtoId<JobPrototype> job, JobPriority priority)
    {
        if (priority == JobPriority.Never)
            SelectedJobPriorities.Remove(job);
        else
            SelectedJobPriorities[job] = priority;

        // Only one high priority job is allowed.
        if (priority == JobPriority.High)
        {
            foreach (var other in SelectedJobPriorities.Keys.ToList())
            {
                if (other != job && SelectedJobPriorities[other] == JobPriority.High)
                    SelectedJobPriorities[other] = JobPriority.Medium;
            }
        }

        UpdateSelectors();
        CheckDirty();
    }

    /// <summary>Keeps duplicated jobs and demoted high-priority jobs in sync.</summary>
    private void UpdateSelectors()
    {
        foreach (var (job, selector) in _selectors)
        {
            selector.Select((int)SelectedJobPriorities.GetValueOrDefault(job, JobPriority.Never));
        }
    }

    /// <summary>A save from another control, or the server correcting us, invalidates the edits.</summary>
    private void OnStateChanged()
    {
        CheckDirty();
    }

    private void CheckDirty()
    {
        var saved = _selection.State.JobPriorities;

        var dirty = SelectedJobPriorities.Count != saved.Count
                    || SelectedJobPriorities.Any(kv => saved.GetValueOrDefault(kv.Key, JobPriority.Never) != kv.Value);

        SaveButton.Disabled = !dirty;
        ResetButton.Disabled = !dirty;
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
            _selection.OnStateChanged -= OnStateChanged;
    }
}
