using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.Lobby.UI;

/// <summary>
/// One department's banner in <see cref="MoffJobPriorityEditor"/>, holding that department's job
/// selectors.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MoffJobPriorityDepartment : BoxContainer
{
    public MoffJobPriorityDepartment(DepartmentPrototype department, bool first)
    {
        RobustXamlLoader.Load(this);

        Name = department.ID;
        Spacer.Visible = !first;

        DepartmentLabel.Text = Loc.GetString(
            "humanoid-profile-editor-department-jobs-label-moffstation",
            ("departmentName", Loc.GetString(department.Name)));

        ((StyleBoxFlat)HeaderPanel.PanelOverride!).BackgroundColor = department.Color;
    }
}
