using Content.Shared.Traits;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI.Roles;

[GenerateTypedNameReferences]
public sealed partial class TraitPreferenceSelector : Control
{
    public int Cost;

    public bool Preference
    {
        get => Checkbox.Pressed;
        set => Checkbox.Pressed = value;
    }

    public event Action<bool>? PreferenceChanged;

    public TraitPreferenceSelector(TraitPrototype trait)
    {
        RobustXamlLoader.Load(this);

        Checkbox.OnToggled += OnCheckBoxToggled;

        var text = Loc.GetString(trait.Name);

        if (trait.Description is not { } descLoc)
            return;

        var desc = Loc.GetString(descLoc);

        Cost = trait.Cost;
        if (trait.Cost != 0)
        {
            Checkbox.ToolTip = $"Cost: [{trait.Cost}]";
        }

        TraitName.Text = text;
        TraitDescription.Text = desc;
    }

    private void OnCheckBoxToggled(BaseButton.ButtonToggledEventArgs args)
    {
        PreferenceChanged?.Invoke(Preference);
    }
}
