using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.CrewManifest.UI;

[GenerateTypedNameReferences]
public sealed partial class CrewManifestEntryControl : BoxContainer
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IEntityManager _entityManager = default!;

    public CrewManifestEntryControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public CrewManifestEntryControl(Content.Shared.CrewManifest.CrewManifestEntry entry)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // Use markup to style the pronouns. This is done so that the name and pronouns can be in one label which wraps
        // nicely. If they're separate controls, wrapping is WAY more complicated.
        var nameMessage = new FormattedMessage();
        nameMessage.AddText(entry.Name);
        nameMessage.AddText(" ");
        nameMessage.PushTag(new MarkupNode("font",
            null,
            new Dictionary<string, MarkupParameter> { ["size"] = new(10L) }));
        nameMessage.PushTag(new MarkupNode("italic", null, null));
        nameMessage.PushColor(Color.Gray);
        nameMessage.AddText(Loc.GetString("gender-display", ("gender", entry.Gender)));
        nameMessage.Pop(); // color
        nameMessage.Pop(); // italic
        nameMessage.Pop(); // font
        NameLabel.SetMessage(nameMessage);

        TitleLabel.SetMessage(entry.JobTitle);

        if (_prototypeManager.TryIndex<JobIconPrototype>(entry.JobIcon, out var jobIcon))
        {
            JobIcon.Texture = _entityManager.System<SpriteSystem>().Frame0(jobIcon.Icon);
            JobIcon.Visible = true;
        }
    }
}
