using Content.Shared.CrewManifest;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CrewManifest.UI;

[GenerateTypedNameReferences]
public sealed partial class CrewManifestSection : BoxContainer
{
    public CrewManifestSection()
    {
        RobustXamlLoader.Load(this);
    }

    public CrewManifestSection(DepartmentPrototype section, List<CrewManifestEntry> entries)
    {
        RobustXamlLoader.Load(this);

        HeaderPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = section.Color };
        HeaderLabel.Text = Loc.GetString(
            "moff-crew-manifest-department-header",
            ("departmentName", Loc.GetString(section.Name))
        );

        foreach (var entry in entries)
        {
            EntryContainer.AddChild(new CrewManifestEntryControl(entry));
        }
    }
}
