- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Bagel
  - Box
  - Fland
  - Marathon
  - Oasis
  - Packed
  - Plasma
  - Reach
  - Exo
  - Snowball
  # Moffstation - Start - Our Maps
  - Amber
  - Omega
  - Meta
  - Frezon
 # - Waterjug
  - Prime
  - Barratry
  - Scylla
  - Aspid
  - Elkridge
  - Wapiti
  # Moffstation - End
