- type: gameMapPool
  id: DefaultMapPoolUpstream # Moffstation - Custom Map Pool
  maps:
  - Bagel
  - Box
  - Elkridge
  - Fland
  - Marathon
  - Oasis
  - Packed
  - Plasma
  - Reach
  - Exo
  - Snowball
  - Serpentcrest
