- type: startingGear
  id: SyndicateFootsoldierGearArmed
  parent: SyndicateOperativeGearCivilian
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    head: ClothingHeadHelmetSwatSyndicate
    outerClothing: ClothingOuterArmorBasic
    gloves: ClothingHandsGlovesColorBlack
    back: ClothingBackpack
    shoes: ClothingShoesBootsCombatFilled
    ears: ClothingHeadsetSyndicateInfiltrator
  storage:
    back:
    - BoxSurvivalSyndicate
  inhand:
  - CombatKnife
