- type: entity
  parent: BaseItem
  id: CardBase
  name: Card
  abstract: true
  categories: [ HideSpawnMenu ]
  components:
  - type: Sprite
    sprite: _EstacaoPirata/Objects/Misc/Cards/card_black.rsi
    state: empty
  - type: Item
    size: Small
  - type: Appearance
  - type: HideInStripMenu
    strategy: !type:HideInStripMenuWithDynamicStrategy
  - type: EmitSoundOnLand
    sound:
      collection: cardShove
  - type: Rotatable
  - type: UseDelay
    delay: 0.5
  - type: Card
    obverseSprite:
    - sprite: _EstacaoPirata/Objects/Misc/Cards/card_black.rsi
      state: singlecard_down
    reverseSprite:
    - sprite: _EstacaoPirata/Objects/Misc/Cards/card_black.rsi
      state: singlecard_down
    flipped: true

- type: entity
  parent: BaseItem
  id: CardHandBase
  categories: [ HideSpawnMenu ]
  name: Hand of Cards
  components:
  - type: Sprite
    sprite: _EstacaoPirata/Objects/Misc/Cards/card_black.rsi
    state: empty
  - type: Item
    size: Small
  - type: Appearance
  - type: HideInStripMenu
    strategy: !type:HideInStripMenuWithDynamicStrategy
  - type: CardHand
    limit: 5
  - type: ContainerContainer
    containers:
      cardstack-container: !type:Container
        showEnts: False
        occludes: True
        ents: []
  - type: UserInterface
    interfaces:
      enum.CardUiKey.Key:
        type: CardHandMenuBoundUserInterface
  - type: ActivatableUI
    key: enum.CardUiKey.Key

- type: entity
  parent: [ BoxCardboard, BaseBagOpenClose ]
  id: CardBoxBase
  abstract: true
  name: Card Box
  categories: [ HideSpawnMenu ]
  components:
  - type: Item
    size: Small
  - type: Sprite
    sprite: _EstacaoPirata/Objects/Misc/Cards/card_black.rsi
    state: empty
  - type: GenericVisualizer
    visuals:
      enum.StorageVisuals.Open:
        base:
          True: { state: box_open }
          False: { state: box }
  - type: Storage
    maxItemSize: Normal
    grid:
    - 0,0,1,1
    whitelist:
      components:
      - CardDeck
  - type: OpenTriggeredStorageFill
    contents:
    - id: CardDeckBase
      amount: 1
  - type: Appearance
  - type: StaticPrice
    price: 25

- type: entity
  parent: BaseItem
  id: CardDeckBase
  categories: [ HideSpawnMenu ]
  name: deck of cards
  components:
  - type: Sprite
    sprite: _EstacaoPirata/Objects/Misc/Cards/card_black.rsi
    state: empty
  - type: Item
    size: Normal
  - type: Appearance
  - type: CardDeck
    limit: 10
  - type: ContainerContainer
    containers:
      cardstack-container: !type:Container
        showEnts: false
        occludes: true
      card-deck: !type:Container
        showEnts: false
        occludes: true
