using System.Linq;
using Content.Client.Chat.Managers;
using Content.Client.UserInterface.Controls;
using Content.Shared.ActionBlocker;
using Content.Shared.Chat;
using Content.Shared.Radio;
using Content.Shared.Radio.Components;
using Content.Shared.Silicons.Laws;
using Content.Shared.Silicons.Laws.Components;
using Content.Shared.Speech;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Silicons.Laws.Ui;

[GenerateTypedNameReferences]
public sealed partial class SiliconLawMenu : FancyWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IChatManager _chatManager = default!;
    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private EntityManager _entityManager = default!;
    [Dependency] private IRobustRandom _random = default!;

    private readonly SharedSiliconLawSystem _lawSystem;

    private static readonly TimeSpan AnnounceBaseCooldown = TimeSpan.FromSeconds(1);
    private static readonly float MinChatCooldown = 1;
    private static readonly float MaxChatCooldown = 2;

    private static readonly List<ChatSelectChannel> SelectableChatChannels =
        new() { ChatSelectChannel.Local, ChatSelectChannel.Whisper };

    private int _selectedChatChannelIdx;
    private readonly List<RadioChannelPrototype> _selectableRadioChannels = new();

    private readonly HashSet<SiliconLaw> _selectedLaws = new();
    private readonly Queue<(SiliconLaw law, TimeSpan announceTime)> _queuedLaws = new();
    private TimeSpan _nextAllowedAnnouncePress = TimeSpan.Zero;

    private EntityUid _owner;

    public SiliconLawMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _lawSystem = _entityManager.System<SiliconLawSystem>();

        LawChatChannelOption.OnItemSelected += OnLawChatChannelSelected;
        LawSelectAllButton.OnPressed += _ => OnMassSelectPressed(true);
        LawSelectNoneButton.OnPressed += _ => OnMassSelectPressed(false);
        LawAnnounceButton.OnPressed += OnLawAnnounceButtonPressed;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var curTime = _timing.CurTime;
        LawAnnounceButton.Disabled = curTime < _nextAllowedAnnouncePress;
        // Don't want to change the channel while currently announcing laws
        LawChatChannelOption.Disabled = curTime < _nextAllowedAnnouncePress;

        // Announce laws
        // Skip if no queued laws or delay still active
        if (_queuedLaws.Count < 1 || _queuedLaws.Peek().announceTime > curTime)
        {
            return;
        }

        var law = _queuedLaws.Dequeue().law;
        var identifier = law.LawIdentifierOverride ?? $"{law.Order}";
        var lawIdentifier = Loc.GetString("laws-ui-law-header", ("id", identifier));
        var lawDescription = Loc.GetString(law.LawString);
        var lawIdentifierPlaintext = FormattedMessage.RemoveMarkupPermissive(lawIdentifier);
        var lawDescriptionPlaintext = FormattedMessage.RemoveMarkupPermissive(lawDescription);

        // Local chat and whisper
        if (_selectedChatChannelIdx < SelectableChatChannels.Count)
        {
            _chatManager.SendMessage($"{lawIdentifierPlaintext}: {lawDescriptionPlaintext}",
                SelectableChatChannels[_selectedChatChannelIdx]);
        }
        // Radio
        else
        {
            var radioChannelProto = _selectableRadioChannels[_selectedChatChannelIdx - SelectableChatChannels.Count];
            var radioMessage = radioChannelProto.ID == SharedChatSystem.CommonChannel
                ? $"{SharedChatSystem.RadioCommonPrefix} {lawIdentifierPlaintext}: {lawDescriptionPlaintext}"
                : $"{SharedChatSystem.RadioChannelPrefix}{radioChannelProto.KeyCode} {lawIdentifierPlaintext}: {lawDescriptionPlaintext}";
            _chatManager.SendMessage(radioMessage, ChatSelectChannel.Radio);
        }
    }

    public void Update(EntityUid uid)
    {
        _owner = uid;
        var laws = _lawSystem.GetBoundLaws(uid);

        laws.Laws.Sort();
        LawDisplayContainer.Children.Clear();
        if (_lawSystem.GetVersion(uid) is {} version )
        {
            Version.Text = Loc.GetString("laws-window-footer-right", ("version", version));
        }

        LawChatChannelOption.Clear();
        foreach (var chatChannel in SelectableChatChannels)
        {
            LawChatChannelOption.AddItem(chatChannel.ToString());
        }

        var channels = _entityManager.TryGetComponent<IntrinsicRadioTransmitterComponent>(uid, out var radio)
            ? new PrototypeFlags<RadioChannelPrototype>(radio.Channels.Select(it => it.Id))
            : [];
        foreach (var radioChannel in channels)
        {
            if (!_prototypeManager.TryIndex<RadioChannelPrototype>(radioChannel, out var radioChannelProto))
                continue;

            _selectableRadioChannels.Add(radioChannelProto);
            LawChatChannelOption.AddItem(Loc.GetString(radioChannelProto.Name));
        }

        LawChatChannelOption.Select(_selectedChatChannelIdx);

        foreach (var law in laws.Laws)
        {
            var control = new LawDisplay(law);
            control.OnPressed += _ =>
            {
                if (_selectedLaws.Contains(law))
                {
                    _selectedLaws.Remove(law);
                    control.SetLawSelectedIndicators(false);
                }
                else
                {
                    _selectedLaws.Add(law);
                    control.SetLawSelectedIndicators(true);
                }
            };

            LawDisplayContainer.AddChild(control);
        }
    }

    private void OnMassSelectPressed(bool isPositive)
    {
        foreach (var child in LawDisplayContainer.Children)
        {
            if (child is not LawDisplay lawDisplay)
                continue;

            if (isPositive)
            {
                _selectedLaws.Add(lawDisplay.Law);
            }
            else
            {
                _selectedLaws.Remove(lawDisplay.Law);
            }

            lawDisplay.SetLawSelectedIndicators(isPositive);
        }
    }

    private void OnLawChatChannelSelected(OptionButton.ItemSelectedEventArgs obj)
    {
        _selectedChatChannelIdx = LawChatChannelOption.GetIdx(obj.Id);
        LawChatChannelOption.Select(_selectedChatChannelIdx);
    }

    private void OnLawAnnounceButtonPressed(BaseButton.ButtonEventArgs obj)
    {
        // If you have no laws selected, or you can't talk, you can't state your laws...
        var cannotSpeak = !_entityManager.TryGetComponent<SpeechComponent>(_owner, out _)
                          || !_entityManager.System<ActionBlockerSystem>().CanSpeak(_owner);
        if (_selectedLaws.Count < 1 || cannotSpeak)
            return;

        var toAnnounce = _selectedLaws.ToList();
        toAnnounce.Sort();

        // Queue up laws to be announced
        // The first message will be sent immediately, while future ones have a cooldown
        var totalChatCooldown = TimeSpan.Zero;
        foreach (var law in toAnnounce)
        {
            var chatCooldown = TimeSpan.FromSeconds(_random.NextFloat(MinChatCooldown, MaxChatCooldown));
            _queuedLaws.Enqueue((law, _timing.CurTime + totalChatCooldown));
            totalChatCooldown += chatCooldown;
        }

        // Disable button until all laws announced, plus an additional cooldown
        _nextAllowedAnnouncePress = _timing.CurTime + totalChatCooldown + AnnounceBaseCooldown;
    }
}
