using System.Linq;
using Content.Client.Humanoid;
using Content.Shared.Clothing;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;

namespace Content.Client.Lobby.UI;

/// <summary>
/// Holds character data on the side of the setup GUI.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CharacterPickerButton : ContainerButton
{
    /// <summary>
    /// Invoked if we should delete the attached character
    /// </summary>
    public event Action? OnDeletePressed;

    /// <summary>
    /// Invoked if we should mark the attached character active or inactive
    /// </summary>
    public event Action<bool>? OnEnableToggled; // Moffstation - Multi-character selection

    public CharacterPickerButton(
        IPrototypeManager prototypeManager,
        ISharedPlayerManager playerMan,
        ButtonGroup group,
        HumanoidCharacterProfile profile,
        bool isSelected,
        bool simple = false) // Moff - Multi-character selection: late join reuses this without the side buttons
    {
        RobustXamlLoader.Load(this);
        AddStyleClass(StyleClassButton);
        ToggleMode = true;
        Group = group;

        View.LoadPreview(profile);

        // Moff Start - Multi-character selection: no job is "High" on a character any more, so the
        // subtitle comes from the player-global priorities instead.
        /*
        var description = profile.Name;

        var highPriorityJob = profile.JobPriorities.SingleOrDefault(p => p.Value == JobPriority.High).Key;
        if (highPriorityJob != default)
        {
            var jobName = prototypeManager.Index(highPriorityJob).LocalizedName;
            description = $"{description}\n{jobName}";
        }
        */
        DescriptionLabel.Text = BuildMoffDescription(profile, prototypeManager);
        // Moff end

        Pressed = isSelected;

        // Moff Start - Multi-character selection: delete becomes a ConfirmButton in a side column
        // shared with the active toggle, built in CharacterPickerButton.MultiCharacter.cs. That
        // hides upstream's DeleteButton/ConfirmDeleteButton rather than replacing them.
        SetupMoffButtons(isSelected, simple);
        // Moff end
    }
}
