using System.Globalization;
using System.Linq; // Moffstation
using Content.Client.Humanoid;
using Content.Client.Message;
using Content.Client.Players.PlayTimeTracking;
using Content.Client.Sprite;
using Content.Shared.CCVar;
using Content.Shared.GameTicking;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Configuration;
using Robust.Shared.ContentPack;
using Robust.Shared.Enums;
using Robust.Shared.Prototypes;
using Direction = Robust.Shared.Maths.Direction;

// CD: Records editor imports
using Content.Client._CD.Records.UI;
using Content.Client.Lobby.UI.Roles;
using Content.Client.Stylesheets;
using Content.Shared._CD.Records;
// End CD - Character Records
using Content.Shared._DV.Traits;
using Robust.Shared.Utility; // DV - Traits

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class HumanoidProfileEditor : BoxContainer
    {
        private readonly IClientPreferencesManager _preferencesManager;
        private readonly IConfigurationManager _cfgManager;
        private readonly IEntityManager _entManager;
        private readonly IFileDialogManager _dialogManager;
        private readonly IPlayerManager _playerManager;
        private readonly IPrototypeManager _prototypeManager;
        private readonly IResourceManager _resManager;
        private readonly MarkingManager _markingManager;
        private readonly JobRequirementsManager _requirements;
        private readonly LobbyUIController _controller;

        private readonly SpriteSystem _sprite;

        // CCvar.
        private int _maxNameLength;

        /// <summary>
        /// If we're attempting to save.
        /// </summary>
        public event Action? Save;

        /// <summary>
        /// The character slot for the current profile.
        /// </summary>
        public int? CharacterSlot;

        /// <summary>
        /// The work in progress profile being edited.
        /// </summary>
        public HumanoidCharacterProfile? Profile;

        private Direction _previewRotation = Direction.North;

        private bool _isDirty;

        public bool IsDirty
        {
            get => _isDirty;
            set
            {
                if (_isDirty == value)
                    return;

                _isDirty = value;
                UpdateSaveButton();
            }
        }

        // CD: Height
        private float _defaultHeight = 1f;

        // CD: Record editor
        private readonly RecordEditorGui _recordsTab;

        private ISawmill _sawmill;

        private MarkingsViewModel _markingsModel = new();

        public HumanoidProfileEditor(
            IClientPreferencesManager preferencesManager,
            IConfigurationManager configurationManager,
            IEntityManager entManager,
            IFileDialogManager dialogManager,
            ILogManager logManager,
            IPlayerManager playerManager,
            IPrototypeManager prototypeManager,
            IResourceManager resManager,
            JobRequirementsManager requirements,
            MarkingManager markings)
        {
            RobustXamlLoader.Load(this);
            _sawmill = logManager.GetSawmill("profile.editor");
            _cfgManager = configurationManager;
            _entManager = entManager;
            _dialogManager = dialogManager;
            _playerManager = playerManager;
            _prototypeManager = prototypeManager;
            _markingManager = markings;
            _preferencesManager = preferencesManager;
            _resManager = resManager;
            _requirements = requirements;
            _controller = UserInterfaceManager.GetUIController<LobbyUIController>();
            _sprite = _entManager.System<SpriteSystem>();

            _maxNameLength = _cfgManager.GetCVar(CCVars.MaxNameLength);
            _allowFlavorText = _cfgManager.GetCVar(CCVars.FlavorText);

            Markings.SetModel(_markingsModel);

            ImportButton.OnPressed += args =>
            {
                ImportProfile();
            };

            ExportButton.OnPressed += args =>
            {
                ExportProfile();
            };

            ExportImageButton.OnPressed += args =>
            {
                ExportImage();
            };

            OpenImagesButton.OnPressed += args =>
            {
                _resManager.UserData.OpenOsWindow(ContentSpriteSystem.Exports);
            };

            ResetButton.OnPressed += args =>
            {
                SetProfile((HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter, _preferencesManager.Preferences?.SelectedCharacterIndex);
            };

            SaveButton.OnPressed += args =>
            {
                Save?.Invoke();
            };

            Traits.OnTraitsChanged += OnTraitsSelectionChanged; // DeltaV
            Antags.OnAntagsChanged += OnAntagsSelectionChanged; // Moffstation
            Antags.OnLoadoutPressed += OnAntagLoadoutPressed; // Moffstation

            #region Left

            #region Name

            NameEdit.OnTextChanged += args => { SetName(args.Text); };
            NameEdit.IsValid = args => args.Length <= _maxNameLength;
            NameRandomize.OnPressed += args => RandomizeName();
            RandomizeEverythingButton.OnPressed += args => { RandomizeEverything(); };
            WarningLabel.SetMarkup($"[color=red]{Loc.GetString("humanoid-profile-editor-naming-rules-warning")}[/color]");

            #endregion Name

            #region Appearance

            TabContainer.SetTabTitle(0, Loc.GetString("humanoid-profile-editor-appearance-tab"));

            #region Sex

            SexButton.OnItemSelected += args =>
            {
                SexButton.SelectId(args.Id);
                SetSex((Sex)args.Id);
            };

            #endregion Sex

            #region Age

            AgeEdit.OnTextChanged += args =>
            {
                if (!int.TryParse(args.Text, out var newAge))
                    return;

                SetAge(newAge);
            };

            #endregion Age

            #region Gender

            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-male-text"), (int)Gender.Male);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-female-text"), (int)Gender.Female);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-epicene-text"), (int)Gender.Epicene);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-neuter-text"), (int)Gender.Neuter);

            PronounsButton.OnItemSelected += args =>
            {
                PronounsButton.SelectId(args.Id);
                SetGender((Gender)args.Id);
            };

            #endregion Gender

            // Umbra re-added this.
            #region Species

            RefreshSpecies();

            SpeciesButton.OnItemSelected += args =>
            {
                SpeciesButton.SelectId(args.Id);
                SetSpecies(_species[args.Id].ID);
                Traits.RefreshTraits(); // DeltaV - Allows for hiding traits
                OnSkinColorOnValueChanged();
            };

            // Umbra re-added this.
            #endregion Species

            #region CDHeight

            CDHeight.OnTextChanged += args =>
            {
                if (Profile is null || !float.TryParse(args.Text, out var newHeight))
                    return;

                var prototype = _prototypeManager.Index(Profile.Species);
                newHeight = MathF.Round(Math.Clamp(newHeight, prototype.MinHeight, prototype.MaxHeight), 2);

                // The percentage between the start and end numbers, aka "inverse lerp"
                var sliderPercent = (newHeight - prototype.MinHeight) /
                                    (prototype.MaxHeight - prototype.MinHeight);
                CDHeightSlider.Value = sliderPercent;

                SetProfileHeight(newHeight);
            };

            CDHeightReset.OnPressed += _ =>
            {
                CDHeight.SetText(_defaultHeight.ToString(CultureInfo.InvariantCulture), true);
            };

            CDHeightSlider.OnValueChanged += _ =>
            {
                if (Profile is null)
                    return;
                var prototype = _prototypeManager.Index(Profile.Species);
                var newHeight = MathF.Round(MathHelper.Lerp(prototype.MinHeight, prototype.MaxHeight, CDHeightSlider.Value), 2);
                CDHeight.Text = newHeight.ToString(CultureInfo.InvariantCulture);
                SetProfileHeight(newHeight);
            };

            #endregion CDHeight

            #region Skin

            Skin.OnValueChanged += _ =>
            {
                OnSkinColorOnValueChanged();
            };

            RgbSkinColorContainer.AddChild(_rgbSkinColorSelector = new ColorSelectorSliders());
            _rgbSkinColorSelector.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv; // defaults color selector to HSV
            _rgbSkinColorSelector.OnColorChanged += _ =>
            {
                OnSkinColorOnValueChanged();
            };

            #endregion

            #region SpawnPriority

            foreach (var value in Enum.GetValues<SpawnPriorityPreference>())
            {
                SpawnPriorityButton.AddItem(Loc.GetString($"humanoid-profile-editor-preference-spawn-priority-{value.ToString().ToLower()}"), (int)value);
            }

            SpawnPriorityButton.OnItemSelected += args =>
            {
                SpawnPriorityButton.SelectId(args.Id);
                SetSpawnPriority((SpawnPriorityPreference)args.Id);
            };

            #endregion SpawnPriority

            #region Eyes

            EyeColorPicker.OnEyeColorPicked += newColor =>
            {
                if (Profile is null)
                    return;
                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithEyeColor(newColor));
                _markingsModel.SetOrganEyeColor(Profile.Appearance.EyeColor);
                ReloadProfilePreview();
            };

            #endregion Eyes

            #endregion Appearance

            #region Jobs

            TabContainer.SetTabTitle(1, Loc.GetString("humanoid-profile-editor-jobs-tab"));

            PreferenceUnavailableButton.AddItem(
                Loc.GetString("humanoid-profile-editor-preference-unavailable-stay-in-lobby-button"),
                (int)PreferenceUnavailableMode.StayInLobby);
            PreferenceUnavailableButton.AddItem(
                Loc.GetString("humanoid-profile-editor-preference-unavailable-spawn-as-overflow-button",
                              ("overflowJob", Loc.GetString(SharedGameTicker.FallbackOverflowJobName))),
                (int)PreferenceUnavailableMode.SpawnAsOverflow);

            PreferenceUnavailableButton.OnItemSelected += args =>
            {
                PreferenceUnavailableButton.SelectId(args.Id);
                Profile = Profile?.WithPreferenceUnavailable((PreferenceUnavailableMode)args.Id);
                SetDirty();
            };

            _jobCategories = new Dictionary<string, BoxContainer>();

            Antags.RefreshAntags(Profile); // Moffstation - Antags
            RefreshJobs();

            #endregion Jobs

            TabContainer.SetTabTitle(2, Loc.GetString("moff-special-roles-tab")); // Moffstation - Expanded non-crew roles

            // RefreshTraits(); // DeltaV

            #region Markings

            TabContainer.SetTabTitle(4, Loc.GetString("humanoid-profile-editor-markings-tab"));

            _markingsModel.MarkingsChanged += (_, _) => OnMarkingChange();
            _markingsModel.MarkingsReset += OnMarkingChange;

            #endregion Markings

            #region CosmaticRecords

            _recordsTab = new RecordEditorGui(UpdateProfileRecords);
            TabContainer.AddChild(_recordsTab);
            TabContainer.SetTabTitle(TabContainer.ChildCount - 1, Loc.GetString("humanoid-profile-editor-cd-records-tab"));

            #endregion CosmaticRecords

            RefreshFlavorText();

            #region Dummy

            SpriteRotateLeft.OnPressed += _ =>
            {
                _previewRotation = _previewRotation.TurnCw();
                SetPreviewRotation(_previewRotation);
            };
            SpriteRotateRight.OnPressed += _ =>
            {
                _previewRotation = _previewRotation.TurnCcw();
                SetPreviewRotation(_previewRotation);
            };

            #endregion Dummy

            #endregion Left

            ShowClothes.OnToggled += args =>
            {
                ReloadPreview();
            };

            SpeciesInfoButton.OnPressed += OnSpeciesInfoButtonPressed;

            UpdateSpeciesGuidebookIcon();
            IsDirty = false;
        }

        // Begin DeltaV - Traits Integration
        /// <summary>
        /// Called when trait selection changes in the TraitsTab.
        /// Updates the profile with the new trait selection.
        /// </summary>
        private void OnTraitsSelectionChanged(HashSet<ProtoId<TraitPrototype>> traits)
        {
            if (Profile is null)
                return;

            // Remove all existing traits - iterate directly over readonly collection
            foreach (var existingTrait in Profile.TraitPreferences)
            {
                Profile = Profile.WithoutTraitPreference(existingTrait, _prototypeManager);
            }

            // Add newly selected traits
            foreach (var trait in traits)
            {
                Profile = Profile.WithTraitPreference(trait.Id, _prototypeManager);
            }

            SetDirty();
        }

        /// <summary>
        /// Updates the traits tab with the current profile's selected traits.
        /// </summary>
        private void UpdateTraitsSelection()
        {
            if (Profile is null)
            {
                Traits.SetSelectedTraits(new HashSet<ProtoId<TraitPrototype>>());
                return;
            }

            // Convert profile's trait preferences (strings) to ProtoId<TraitPrototype>
            var selectedTraits = new HashSet<ProtoId<TraitPrototype>>(Profile.TraitPreferences.Count);
            foreach (var traitId in Profile.TraitPreferences)
            {
                // Validate that the trait still exists in prototypes
                if (_prototypeManager.HasIndex(traitId))
                {
                    selectedTraits.Add(new ProtoId<TraitPrototype>(traitId));
                }
            }

            Traits.SetSelectedTraits(selectedTraits);
            Traits.UpdateConditions(Profile.Species);
        }

        /// <summary>
        /// Refreshes the flavor text editor status.
        /// </summary>
        // public void RefreshTraits()
        // {
        //     TraitsList.RemoveAllChildren();
        //
        //     var traits = _prototypeManager.EnumeratePrototypes<TraitPrototype>().OrderBy(t => Loc.GetString(t.Name)).ToList();
        //     TabContainer.SetTabTitle(3, Loc.GetString("humanoid-profile-editor-traits-tab"));
        //
        //     if (traits.Count < 1)
        //     {
        //         TraitsList.AddChild(new Label
        //         {
        //             Text = Loc.GetString("humanoid-profile-editor-no-traits"),
        //             FontColorOverride = Color.Gray,
        //         });
        //         return;
        //     }
        //
        //     // Setup model
        //     Dictionary<string, List<string>> traitGroups = new();
        //     List<string> defaultTraits = new();
        //     traitGroups.Add(TraitCategoryPrototype.Default, defaultTraits);
        //
        //     foreach (var trait in traits)
        //     {
        //         // Begin DeltaV Additions - Species trait exclusion
        //         if (Profile?.Species is { } selectedSpecies && trait.ExcludedSpecies.Contains(selectedSpecies))
        //         {
        //             Profile = Profile?.WithoutTraitPreference(trait.ID, _prototypeManager);
        //             continue;
        //         }
        //         // End DeltaV Additions
        //
        //         if (trait.Category == null)
        //         {
        //             defaultTraits.Add(trait.ID);
        //             continue;
        //         }
        //
        //         if (!_prototypeManager.HasIndex(trait.Category))
        //             continue;
        //
        //         var group = traitGroups.GetOrNew(trait.Category);
        //         group.Add(trait.ID);
        //     }
        //
        //     // Create UI view from model
        //     foreach (var (categoryId, categoryTraits) in traitGroups)
        //     {
        //         TraitCategoryPrototype? category = null;
        //
        //         if (categoryId != TraitCategoryPrototype.Default)
        //         {
        //             category = _prototypeManager.Index<TraitCategoryPrototype>(categoryId);
        //             // Label
        //             TraitsList.AddChild(new Label
        //             {
        //                 Text = Loc.GetString(category.Name),
        //                 Margin = new Thickness(0, 10, 0, 0),
        //                 StyleClasses = { StyleClass.LabelHeading },
        //             });
        //         }
        //
        //         List<TraitPreferenceSelector?> selectors = new();
        //         var selectionCount = 0;
        //
        //         foreach (var traitProto in categoryTraits)
        //         {
        //             var trait = _prototypeManager.Index<TraitPrototype>(traitProto);
        //             var selector = new TraitPreferenceSelector(trait);
        //
        //             selector.Preference = Profile?.TraitPreferences.Contains(trait.ID) == true;
        //             if (selector.Preference)
        //                 selectionCount += trait.Cost;
        //
        //             selector.PreferenceChanged += preference =>
        //             {
        //                 if (preference)
        //                 {
        //                     Profile = Profile?.WithTraitPreference(trait.ID, _prototypeManager);
        //                 }
        //                 else
        //                 {
        //                     Profile = Profile?.WithoutTraitPreference(trait.ID, _prototypeManager);
        //                 }
        //
        //                 SetDirty();
        //                 RefreshTraits(); // If too many traits are selected, they will be reset to the real value.
        //             };
        //             selectors.Add(selector);
        //         }
        //
        //         // Selection counter
        //         if (category is { MaxTraitPoints: >= 0 })
        //         {
        //             TraitsList.AddChild(new Label
        //             {
        //                 Text = Loc.GetString("humanoid-profile-editor-trait-count-hint", ("current", selectionCount) ,("max", category.MaxTraitPoints)),
        //                 FontColorOverride = Color.Gray
        //             });
        //         }
        //
        //         foreach (var selector in selectors)
        //         {
        //             if (selector == null)
        //                 continue;
        //
        //             if (category is { MaxTraitPoints: >= 0 } &&
        //                 selector.Cost + selectionCount > category.MaxTraitPoints)
        //             {
        //                 selector.Checkbox.Label.FontColorOverride = Color.Red;
        //             }
        //
        //             TraitsList.AddChild(selector);
        //         }
        //     }
        // }
        // End DeltaV - Traits Integration

        // Moffstation - Start - Antags
        public void RefreshAntags()
        {
            Antags.RefreshAntags(Profile);
        }

        private void OnAntagsSelectionChanged(HashSet<ProtoId<AntagPrototype>> antags) // Moffstation
        {
            if (Profile is null)
                return;

            Profile = Profile.WithAntagPreferences(antags);
            SetDirty();
        }
        // Moffstation - End

        private void SetDirty()
        {
            // If it equals default then reset the button.
            if (Profile == null || _preferencesManager.Preferences?.SelectedCharacter.MemberwiseEquals(Profile) == true)
            {
                IsDirty = false;
                return;
            }

            // TODO: Check if profile matches default.
            IsDirty = true;
        }

        /// <summary>
        /// Reloads the entire dummy entity for preview.
        /// </summary>
        /// <remarks>
        /// This is expensive so not recommended to run if you have a slider.
        /// </remarks>
        private void ReloadPreview()
        {
            if (Profile == null)
                return;

            SpriteView.LoadPreview(Profile, JobOverride, ShowClothes.Pressed);

            // Check and set the dirty flag to enable the save/reset buttons as appropriate.
            SetDirty();
        }

        /// <summary>
        /// Resets the profile to the defaults.
        /// </summary>
        public void ResetToDefault()
        {
            SetProfile(
                (HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter,
                _preferencesManager.Preferences?.SelectedCharacterIndex);
        }

        /// <summary>
        /// Sets the editor to the specified profile with the specified slot.
        /// </summary>
        public void SetProfile(HumanoidCharacterProfile? profile, int? slot)
        {
            Profile = profile?.Clone();
            CharacterSlot = slot;
            IsDirty = false;
            JobOverride = null;

            UpdateNameEdit();
            UpdateFlavorTextEdit();
            UpdateSexControls();
            UpdateGenderControls();
            UpdateSkinColor();
            UpdateSpawnPriorityControls();
            UpdateAgeEdit();
            UpdateEyePickers();
            UpdateSaveButton();
            UpdateMarkings();

            // CD: our controls
            UpdateHeightControls();
            _recordsTab.Update(profile);

            UpdateTraitsSelection(); // DeltaV - Traits

            Antags.RefreshAntags(Profile); // Moffstation - Antags
            RefreshJobs();
            RefreshLoadouts();
            RefreshSpecies();
            // RefreshTraits(); // DeltaV
            RefreshFlavorText();
            ReloadPreview();

            if (Profile != null)
            {
                PreferenceUnavailableButton.SelectId((int)Profile.PreferenceUnavailable);
            }
        }

        /// <summary>
        /// A slim reload that only updates the entity itself and not any of the job entities, etc.
        /// </summary>
        private void ReloadProfilePreview()
        {
            if (Profile == null)
                return;

            SpriteView.ReloadProfilePreview(Profile);

            // Check and set the dirty flag to enable the save/reset buttons as appropriate.
            SetDirty();
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (!disposing)
                return;

            _loadoutWindow?.Dispose();
            _loadoutWindow = null;
        }

        protected override void EnteredTree()
        {
            base.EnteredTree();
            ReloadPreview();
        }

        private void UpdateSaveButton()
        {
            SaveButton.Disabled = Profile is null || !IsDirty;
            ResetButton.Disabled = Profile is null || !IsDirty;
        }

        private void SetPreviewRotation(Direction direction)
        {
            SpriteView.OverrideDirection = (Direction)((int)direction % 4 * 2);
        }
    }
}
