using Content.Shared._Moffstation.AacTablet;
using Content.Shared.DeltaV.QuickPhrase;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Moffstation.AacTablet.UI;

[GenerateTypedNameReferences]
public sealed partial class AacPhraseButtonsGroup : BoxContainer
{
    public AacPhraseButtonsGroup()
    {
        RobustXamlLoader.Load(this);
    }

    public static AacPhraseButtonsGroup Create(
        AacTabletPhraseGroup group,
        Action<ProtoId<QuickPhrasePrototype>> onPressed,
        int containerWidth
    )
    {
        var ret = new AacPhraseButtonsGroup();
        ret.Label.Text = group.Name;
        foreach (var phrase in group.Phrases)
        {
            ret.ButtonGrid.AddChild(AacPhraseButton.Create(phrase, onPressed, containerWidth, ret.ButtonGrid.Columns));
        }

        return ret;
    }
}
