using System.Linq;
using Content.Client.UserInterface.ControlExtensions;
using Content.Shared._Moffstation.AacTablet;
using Content.Shared.DeltaV.QuickPhrase;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Moffstation.AacTablet.UI;

[GenerateTypedNameReferences]
public sealed partial class AacPhraseSearchTab : BoxContainer
{
    [Dependency] private EntityManager _entMan = default!;
    private readonly AacTabletSystem _aacTablet;

    private ProtoId<QuickPhrasePrototype>? _firstPhrase;

    public event Action<ProtoId<QuickPhrasePrototype>>? OnPhrasePressed;

    public AacPhraseSearchTab()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        _aacTablet = _entMan.System<AacTabletSystem>();

        SearchText.OnTextChanged += UpdateContent;
        SearchText.OnTextEntered += SendFirstPhraseAndClear;
    }

    private void UpdateContent(LineEdit.LineEditEventArgs args)
    {
        var width = this.GetControlOfType<AacWindow>(true).FirstOrDefault()?.MinWidth ?? 540;
        Content.Children.Clear();
        _firstPhrase = null;
        foreach (var group in _aacTablet.SearchPhrases(args.Text))
        {
            _firstPhrase ??= group.Phrases.First();
            Content.Children.Add(AacPhraseButtonsGroup.Create(group, OnPressed, (int)width));
        }
    }

    private void SendFirstPhraseAndClear(LineEdit.LineEditEventArgs args)
    {
        if (_firstPhrase is { } firstPhrase)
        {
            OnPressed(firstPhrase);
        }

        SearchText.Clear();
    }

    private void OnPressed(ProtoId<QuickPhrasePrototype> phrase)
    {
        OnPhrasePressed?.Invoke(phrase);
    }
}
