using Content.Shared._Moffstation.AacTablet;
using Content.Shared.DeltaV.QuickPhrase;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Moffstation.AacTablet.UI;

[GenerateTypedNameReferences]
public sealed partial class AacPhraseButtonsTab : ScrollContainer
{
    public AacPhraseButtonsTab()
    {
        RobustXamlLoader.Load(this);
    }

    public static AacPhraseButtonsTab Create(
        AacTabletPhraseTab tab,
        Action<ProtoId<QuickPhrasePrototype>> onPressed,
        int containerWidth
    )
    {
        var ret = new AacPhraseButtonsTab();
        foreach (var group in tab.Groups)
        {
            ret.Content.Children.Add(AacPhraseButtonsGroup.Create(group, onPressed, containerWidth));
        }

        return ret;
    }
}
