using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Moffstation.AacTablet;
using Content.Shared.DeltaV.QuickPhrase;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Moffstation.AacTablet.UI;

[GenerateTypedNameReferences]
public sealed partial class AacWindow : FancyWindow
{
    [Dependency] private EntityManager _entMan = default!;

    public event Action<ProtoId<QuickPhrasePrototype>>? PhraseButtonPressed;

    public AacWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        SearchTab.OnPhrasePressed += OnButtonPressed;
        Tabs.SetTabTitle(0, Loc.GetString("phrase-tab-search"));
        foreach (var (index, tab) in _entMan.System<AacTabletSystem>().GetPhrases().Index())
        {
            Tabs.AddChild(AacPhraseButtonsTab.Create(tab, OnButtonPressed, (int)MinWidth));
            Tabs.SetTabTitle(index + 1, tab.Name);
        }
    }

    private void OnButtonPressed(ProtoId<QuickPhrasePrototype> phrase)
    {
        PhraseButtonPressed?.Invoke(phrase);
    }
}
