using System.Linq;
using System.Numerics;
using Content.Client._Moffstation.Voting.Ui;
using Content.Client.UserInterface.Controls;
using Content.Shared._ES.Voting;
using Content.Shared._ES.Voting.Components;
using Content.Shared._Moffstation.Voting.Components;
using Content.Shared._Moffstation.Voting.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ES.Voting.Ui;

// Moffstation - we rewrote alot of this for enrollable stuff
[GenerateTypedNameReferences]
public sealed partial class ESVotingWindow : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    private readonly MoffSharedVoteEntrySystem _sharedVote;

    private List<Entity<MoffVoteEntryComponent>> _lastEntries = new();

    // Moff - enroll actions, bubbled up from the entry controls for the BUI to send.
    public Action<EntityUid, bool>? OnSetEnroll;
    public Action<EntityUid, bool>? OnSetRandom;
    public Action<EntityUid>? OnEarlyStartEnroll;

    public ESVotingWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sharedVote = _entityManager.System<MoffSharedVoteEntrySystem>();
    }

    public void Update(EntityUid owner)
    {
        var entries = _sharedVote.EnumerateEntries().ToList();

        if (entries.Count != _lastEntries.Count || entries.Intersect(_lastEntries).Count() != entries.Count)
        {
            VotesContainer.Children.Clear();
            foreach (var entry in entries)
            {
                if (GenerateControl(entry) is not { } control)
                    continue;
                VotesContainer.AddChild(control);
            }
        }

        _lastEntries = entries;

        foreach (var child in VotesContainer.Children)
        {
            if (child is IVoteEntryControl ctrl)
                ctrl.Update(owner);
        }
        // PB and B
        VotesContainer.InvalidateMeasure();
    }

    // Moffstation - build the control for a vote entry based on its concrete type
    private Control? GenerateControl(Entity<MoffVoteEntryComponent> ent)
    {
        if (_entityManager.HasComponent<ESVoteComponent>(ent.Owner))
            return new ESVoteControl(ent.Owner);

        if (_entityManager.TryGetComponent<MoffEnrollEventComponent>(ent.Owner, out var enroll))
        {
            var control = new MoffEnrollControl((ent.Owner, enroll));
            control.OnSetEnroll += enrolled => OnSetEnroll?.Invoke(ent.Owner, enrolled);
            control.OnSetRandom += random => OnSetRandom?.Invoke(ent.Owner, random);
            control.EarlyStartEnroll += () => OnEarlyStartEnroll?.Invoke(ent.Owner);
            return control;
        }

        return null;
    }
}

