- type: gameMapPool
  id: DefaultMapPool
  maps:
  # Deadpop (0-15 Pop)
  - Reach
  # Ultra-Low Pop (11-35 Pop)
  - Dove
  - Frezon
  - Jellyfish
  - Ossuary
  # Low Pop (26-60 Pop)
  - Amber
  - Elkridge
  - Omega
  - Packed
  # Medium Pop (41-75 Pop)
  - Aspid
  - Bagel
  - Barratry
  - Lambda
  - Marathon
  - Plasma
  - Prime
  - Scylla
  - Wapiti
  # High Pop (61-95 Pop)
  - Box
  - Exo
  - Meta
  - Skeld
  # Ultra-High Pop (+81 Pop)
  - Fland
  - Oasis
  - Serpentcrest
