using Content.Client.Message;
using Content.Shared._tc14.Skills.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._tc14.UI;

//TODO saving and stuff
[GenerateTypedNameReferences]
public sealed partial class SkillPicker : BoxContainer
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private int _passionPoints = 5;
    private IEnumerable<SkillPrototype> _skills;

    public SkillPicker()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _skills = _prototypeManager.EnumeratePrototypes<SkillPrototype>();
        BuildEntries();
        UpdatePassions();
    }

    private void BuildEntries()
    {
        foreach (var skill in _skills)
        {
            var skillNameLabel = new RichTextLabel
            {
                Margin = new Thickness(0, 0, 10, 0),
            };
            skillNameLabel.SetMarkup(Loc.GetString(skill.Name));
            SkillPassionContainer.AddChild(skillNameLabel);

            var passionSpinBox = new SpinBox
            {
                HorizontalAlignment = HAlignment.Center,
                HorizontalExpand = true,
                Value = 0,
                IsValid = val => val is >= 0 and <= 3,
            };
            passionSpinBox.InitDefaultButtons();
            passionSpinBox.ValueChanged += _ => UpdatePassions();
            SkillPassionContainer.AddChild(passionSpinBox);
        }
    }

    private void UpdatePassions()
    {
        var pointsSum = 0;
        foreach (var control in SkillPassionContainer.Children)
        {
            if (control is SpinBox box)
                pointsSum += box.Value;
        }
        SkillPassionPointsLabel.Text = Loc.GetString("skills-passionmenu-label",
            ("points", pointsSum),
            ("maxPoints", _passionPoints));
        if (pointsSum < _passionPoints)
        {
            SkillPassionPointsLabel.Modulate = Color.Yellow;
        }
        else if (pointsSum == _passionPoints)
        {
            SkillPassionPointsLabel.Modulate = Color.White;
        }
        else
        {
            SkillPassionPointsLabel.Modulate = Color.Red;
        }
    }
}
