using Content.Client.RichText;
using Content.Shared.Silicons.Laws;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Moffstation.Robotics.LawProgrammer;

[GenerateTypedNameReferences]
public sealed partial class LawProgrammerLawDisplay : Control
{
    public LawProgrammerLawDisplay(SiliconLaw law)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var identifier = law.LawIdentifierOverride ?? $"{law.Order}";
        var lawIdentifier = Loc.GetString("laws-ui-law-header", ("id", identifier));
        var lawDescription = Loc.GetString(law.LawString);

        LawNumberLabel.SetMessage(
            FormattedMessage.FromMarkupPermissive(lawIdentifier),
            UserFormattableTags.SiliconAllowedTags,
            Color.MediumVioletRed);
        LawLabel.SetMessage(
            FormattedMessage.FromMarkupPermissive(lawDescription),
            UserFormattableTags.SiliconAllowedTags,
            Color.AliceBlue);
    }
}
