using Content.Client.UserInterface.Controls;
using Content.Shared._Moffstation.Robotics.LawProgrammer;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.Robotics.LawProgrammer;

[GenerateTypedNameReferences]
public sealed partial class LawProgrammerWindow : FancyWindow
{
    public LawProgrammerWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Update(LawProgrammerBuiState state)
    {
        if (state.Name is { } name)
            LawsetNameLabel.SetMessage(name, Color.Green);
        else
            LawsetNameLabel.SetMessage(Loc.GetString("law-programmer-ui-absent-lawset-label"));

        LawDisplayContainer.RemoveAllChildren();

        if (state.Laws == null || state.Laws.Count == 0)
        {
            LockScreen.Visible = true;
            LawDisplayContainer.Visible = false;
            return;
        }

        LockScreen.Visible = false;
        LawDisplayContainer.Visible = true;

        state.Laws.Sort();
        foreach (var law in state.Laws)
        {
            LawDisplayContainer.AddChild(new LawProgrammerLawDisplay(law));
        }
    }
}
