using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._tc14.Research.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._tc14.Research.UI.Kit;

[GenerateTypedNameReferences]
public sealed partial class ResearchKitWindow : FancyWindow
{
    public ResearchKitWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateState(List<ResearchKitBounty> bounties)
    {
        ResearchKitBountiesList.RemoveAllChildren();
        foreach (var bounty in bounties)
        {
            ResearchKitBountiesList.AddChild(new ResearchKitBountyItem(bounty));
        }
        ResearchKitBountiesList.AddChild(new BoxContainer{SetSize = new Vector2(5, 0)}); // adds a separation extension below
    }
}
