using System.Numerics;
using Content.Shared._tc14.Research.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._tc14.Research.UI.Kit;

[GenerateTypedNameReferences]
public sealed partial class ResearchKitBountyItem : BoxContainer
{
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IPrototypeManager _protoMan = default!;
    private readonly SpriteSystem _sprite;

    private ResearchKitBounty _bounty;

    public ResearchKitBountyItem(ResearchKitBounty bounty)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprite = _entMan.System<SpriteSystem>();
        _bounty = bounty;
        var bountyProto = _protoMan.Index(_bounty.BountyPrototype);
        ResearchBountySpriteView.SetPrototype(bountyProto.SpriteEntity);
        ResearchBountyNameLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString(bountyProto.Name)));
        ResearchBountyProgress.Text = Loc.GetString("researchbounty-progress", ("progress", _bounty.Progress), ("total", bountyProto.MaxAmount));
        foreach (var (disciplineId, points) in bountyProto.RewardedPoints)
        {
            if (!_protoMan.Resolve(disciplineId, out var proto))
                continue;
            var box = new BoxContainer
            {
                SeparationOverride = 5,
            };
            var icon = new TextureRect
            {
                Texture = _sprite.Frame0(proto.Icon),
                TextureScale = new Vector2(2, 2),
                VerticalAlignment = VAlignment.Center,
            };
            var label = new Label
            {
                Text = points.ToString(),
            };
            box.AddChild(icon);
            box.AddChild(label);
            ResearchItemRewardBoxContainer.AddChild(box);
        }
    }
}
