using System.Globalization;
using System.Linq;
using Content.Shared.Atmos;
using Content.Shared.Atmos.EntitySystems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Atmos.UI
{
    /// <summary>
    /// Client-side UI used to control a gas filter.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class GasFilterWindow : DefaultWindow
    {

        public event Action<bool>? ToggleStatusButtonPressed;
        public event Action<string>? FilterTransferRateChanged;
        public event Action<Gas, bool>? FilterGasToggled;

        private readonly Dictionary<Gas, Button> _gasButtons = new();

        public GasFilterWindow()
        {
            RobustXamlLoader.Load(this);

            var atmos = IoCManager.Resolve<EntityManager>().System<SharedAtmosphereSystem>();

            ToggleStatusButton.OnToggled += _ => ToggleStatusButtonPressed?.Invoke(ToggleStatusButton.Pressed);

            FilterTransferRateInput.OnTextChanged += _ => SetFilterRate.Disabled = false;
            SetFilterRate.OnPressed += _ =>
            {
                FilterTransferRateChanged?.Invoke(FilterTransferRateInput.Text);
                SetFilterRate.Disabled = true;
            };

            foreach (var gas in Enum.GetValues<Gas>())
            {
                var button = new Button
                {
                    Text = Loc.GetString(atmos.GetGas(gas).Name),
                    ToggleMode = true,
                };
                _gasButtons[gas] = button;
                button.OnToggled += args => FilterGasToggled?.Invoke(gas, args.Pressed);
                FilteredGasesList.AddChild(button);
            }
        }

        public void SetTransferRate(float rate)
        {
            FilterTransferRateInput.Text = rate.ToString(CultureInfo.CurrentCulture);
        }

        public void SetFilterStatus(bool enabled)
        {
            ToggleStatusButton.Pressed = enabled;
        }

        // Moffstation - Begin (filter multiple gases)
        public void SetFilteredGases(IEnumerable<Gas> filtered)
        {
            foreach (var gas in filtered)
            {
                _gasButtons[gas].Pressed = true;
            }
        }
        // Moffstation - End
    }
}
