using System.Globalization;
using Content.Shared.Atmos;
using Content.Shared.Atmos.EntitySystems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Atmos.UI
{
    /// <summary>
    /// Client-side UI used to control a gas filter.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class GasFilterWindow : DefaultWindow
    {
        // Moff start - Filter multiple gasses
        // private readonly ButtonGroup _buttonGroup = new();

        // public string? SelectedGas;
        // public string? CurrentGasId;
        // Moff end

        public event Action<bool>? ToggleStatusButtonPressed;
        public event Action<string>? FilterTransferRateChanged;
        // public event Action? SelectGasPressed; // Moff - Filter multiple gasses

        public event Action<Gas, bool>? FilterGasToggled; // Moff - Filter multiple gasses

        private readonly Dictionary<Gas, Button> _gasButtons = new(); // Moff - Filter multiple gasses

        public GasFilterWindow()
        {
            RobustXamlLoader.Load(this);

            var atmos = IoCManager.Resolve<EntityManager>().System<SharedAtmosphereSystem>(); // Moff - Filter multiple gasses

            ToggleStatusButton.OnToggled += _ => ToggleStatusButtonPressed?.Invoke(ToggleStatusButton.Pressed);

            FilterTransferRateInput.OnTextChanged += _ => SetFilterRate.Disabled = false;
            SetFilterRate.OnPressed += _ =>
            {
                FilterTransferRateChanged?.Invoke(FilterTransferRateInput.Text);
                SetFilterRate.Disabled = true;
            };

            // Moff start - Filter multiple gasses
            // SelectGasButton.OnPressed += _ => SelectGasPressed?.Invoke();

            // GasList.OnItemSelected += GasListOnItemSelected;
            // GasList.OnItemDeselected += GasListOnItemDeselected;

            foreach (var gas in Enum.GetValues<Gas>())
            {
                var button = new Button
                {
                    Text = Loc.GetString(atmos.GetGas(gas).Name),
                    ToggleMode = true,
                };
                _gasButtons[gas] = button;
                button.OnToggled += args => FilterGasToggled?.Invoke(gas, args.Pressed);
                FilteredGasesList.AddChild(button);
            }
            // Moff end
        }

        public void SetTransferRate(float rate)
        {
            FilterTransferRateInput.Text = rate.ToString(CultureInfo.CurrentCulture);
        }

        public void SetFilterStatus(bool enabled)
        {
            ToggleStatusButton.Pressed = enabled;
        }

        // Moffstation - Begin (filter multiple gases)
        public void SetFilteredGases(IEnumerable<Gas> filtered)
        {
            foreach (var gas in filtered)
            {
                _gasButtons[gas].Pressed = true;
            }
        }

        // public void SetGasFiltered(string? id, string name)
        // {
        //     CurrentGasId = id;
        //     CurrentGasLabel.Text = Loc.GetString("comp-gas-filter-ui-filter-gas-current") + $" {name}";
        //     GasList.ClearSelected();
        //     SelectGasButton.Disabled = true;
        // }
        //
        // public void PopulateGasList(IEnumerable<GasPrototype> gases)
        // {
        //     GasList.Add(new ItemList.Item(GasList)
        //     {
        //         Metadata = null,
        //         Text = Loc.GetString("comp-gas-filter-ui-filter-gas-none")
        //     });
        //
        //     foreach (var gas in gases)
        //     {
        //         var gasName = Loc.GetString(gas.Name);
        //         GasList.Add(GetGasItem(gas.ID, gasName, GasList));
        //     }
        // }
        //
        // private static ItemList.Item GetGasItem(string id, string name, ItemList itemList)
        // {
        //     return new(itemList)
        //     {
        //         Metadata = id,
        //         Text = name
        //     };
        // }
        //
        // private void GasListOnItemSelected(ItemList.ItemListSelectedEventArgs obj)
        // {
        //     SelectedGas = (string) obj.ItemList[obj.ItemIndex].Metadata!;
        //     if(SelectedGas != CurrentGasId) SelectGasButton.Disabled = false;
        // }
        //
        // private void GasListOnItemDeselected(ItemList.ItemListDeselectedEventArgs obj)
        // {
        //     SelectedGas = CurrentGasId;
        //     SelectGasButton.Disabled = true;
        // }
        // Moffstation - End
    }
}
