using Content.Client.Administration.Managers;
using Content.Client.Message;
using Content.Shared._Moffstation.Voting.Components;
using Content.Shared._Moffstation.Warp;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Moffstation.Voting.Ui;

[GenerateTypedNameReferences]
public sealed partial class MoffEnrollControl : PanelContainer, IVoteEntryControl
{
    [Dependency] private IClientAdminManager _admin = default!;
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private IPlayerManager _player = default!;

    private Entity<MoffEnrollEventComponent> _enroller;
    private TimeSpan _endTime;

    /// <summary>
    /// Toggled enrollment, and the character-select window's random pick. The BUI owning this control turns
    /// these into messages; controls don't talk to the server themselves.
    /// </summary>
    public Action<bool>? OnSetEnroll;

    public Action<bool>? OnSetRandom;

    public Action? EarlyStartEnroll;

    public MoffEnrollControl()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }
    public MoffEnrollControl(Entity<MoffEnrollEventComponent> enroller)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _enroller = enroller;
        _endTime = enroller.Comp.EndTime;

        var metadata = _entityManager.GetComponent<MetaDataComponent>(_enroller);
        VoteNameLabel.SetMarkup(Loc.GetString("moff-vote-enroll-header-text-format",
            ("color", enroller.Comp.TitleColor),
            ("title", metadata.EntityName)));
        VoteDescriptionLabel.SetMarkup(Loc.GetString("moff-vote-enroll-header-desc-format",
            ("color", enroller.Comp.DescriptionColor),
            ("desc", metadata.EntityDescription)));

        GotoButton.Disabled = enroller.Comp.WarpTarget is null;

        CharacterSelectionButton.Visible = enroller.Comp.CharacterSelection;

        TimerProgress.MinValue = (float) (enroller.Comp.EndTime - enroller.Comp.Duration).TotalSeconds;
        TimerProgress.MaxValue = (float) enroller.Comp.EndTime.TotalSeconds;

        Refresh();

        EnrollButton.OnPressed += args =>
        {
            EnrollButton.Text = GetEnrollText(args.Button.Pressed);
            OnSetEnroll?.Invoke(args.Button.Pressed);
        };

        // Ghosts only; only they carry a WarpComponent, so the warp system ignores anyone still in a body.
        GotoButton.OnPressed += _ =>
        {
            if (_enroller.Comp.WarpTarget is { } target)
                _entityManager.System<SharedWarpSystem>().RequestWarpToLocation(target);
        };

        CharacterSelectionButton.OnPressed += _ =>
        {
            var window = new MoffCharacterSelectWindow(_enroller);
            window.OnSetRandom += random => OnSetRandom?.Invoke(random);
            window.OpenCentered();
        };

        EarlyStartEnrollButton.OnPressed += _ => EarlyStartEnroll?.Invoke();

        _admin.AdminStatusUpdated += RefreshAdminButton;
        RefreshAdminButton();
    }

    private void RefreshAdminButton()
    {
        EarlyStartEnrollButton.Visible = _admin.HasFlag(AdminFlags.Fun);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
            _admin.AdminStatusUpdated -= RefreshAdminButton;
    }

    public void Update(EntityUid owner)
    {
        Refresh();
    }

    private static string GetEnrollText(bool enrolled)
    {
        return Loc.GetString(enrolled ? "moff-vote-enroll-button-enrolled" : "moff-vote-enroll-button-enroll");
    }

    private void Refresh()
    {
        var enrolled = _player.LocalEntity is { } localEntity && _enroller.Comp.Enrolled.Contains(localEntity);

        EnrollButton.Pressed = enrolled;
        EnrollButton.Text = GetEnrollText(enrolled);

        var enrollCount = _enroller.Comp.Enrolled.Count;
        var maxEnrolled = _enroller.Comp.MaxEnrolled;
        var minEnrolled = _enroller.Comp.MinEnrolled;

        EnrollProgress.MaxValue = Math.Max(1, minEnrolled);
        EnrollProgress.Value = enrollCount;

        EnrollCount.Text = Loc.GetString("moff-vote-enroll-count",
            ("count", enrollCount),
            ("min", minEnrolled),
            ("max", maxEnrolled));
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var curTime = _timing.CurTime;
        var remaining = _endTime - curTime;
        if (remaining <= TimeSpan.Zero)
        {
            TimerProgress.Visible = false;
            TimeLabel.Visible = false;
            return;
        }

        TimeLabel.Text = Loc.GetString("moff-vote-enroll-time-remaining", ("time", $"{remaining:mm\\:ss}"));
        TimerProgress.Value = (float) curTime.TotalSeconds;
    }
}

