using Content.Client.Lobby;
using Content.Client.Lobby.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared._Moffstation.Voting.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Moffstation.Voting.Ui;

/// <summary>
/// Lets a player pick which character they'll spawn as for an enroll vote, mid-round, without going back to
/// the lobby. Picking one of their own just selects it like the lobby does - the antag spawn path already
/// reads the selected character. "Random" is per-vote, and is the only bit the server needs telling about.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MoffCharacterSelectWindow : FancyWindow
{
    [Dependency] private IClientPreferencesManager _preferences = default!;
    [Dependency] private IPrototypeManager _proto = default!;
    [Dependency] private ISharedPlayerManager _player = default!;
    [Dependency] private IEntityManager _entityManager = default!;

    private static readonly SpriteSpecifier DiceIconSpecifier =
        new SpriteSpecifier.Rsi(new ResPath("/Textures/Objects/Fun/dice.rsi"), "d6_6");

    private readonly EntityUid _enroller;

    /// <summary>
    /// Whether the player wants a randomly generated character. Forwarded up to the BUI, which sends it.
    /// </summary>
    public Action<bool>? OnSetRandom;

    public MoffCharacterSelectWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public MoffCharacterSelectWindow(EntityUid enroller)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SetDiceIcon();

        _enroller = enroller;

        // Toggling it back off just falls through to whichever character they have selected.
        RandomButton.OnPressed += args =>
        {
            OnSetRandom?.Invoke(args.Button.Pressed);
            Close();
        };

        ReloadCharacterPickers();
    }

    /// <summary>
    /// Done here because TexturePath loads a raw PNG, which warns for files inside an RSI.
    /// </summary>
    private void SetDiceIcon()
    {
        DiceIcon.Texture = _entityManager.System<SpriteSystem>()
            .Frame0(DiceIconSpecifier);
    }

    /// <summary>
    /// Disposes and rebuilds every picker button from the preferences data.
    /// </summary>
    private void ReloadCharacterPickers()
    {
        Characters.RemoveAllChildren();

        if (!_preferences.ServerDataLoaded || _preferences.Preferences is not { } preferences)
            return;

        var random = PrefersRandom();
        RandomButton.Pressed = random;

        var group = new ButtonGroup();
        var selectedSlot = preferences.SelectedCharacterIndex;

        foreach (var (slot, character) in preferences.Characters)
        {
            // While random is picked, none of their own characters is what they'd spawn as.
            var button = new CharacterPickerButton(_proto, _player, group, character, !random && slot == selectedSlot);

            // This picker only picks; managing characters stays in the lobby.
            button.DeleteButton.Visible = false;

            Characters.AddChild(button);

            button.OnPressed += _ =>
            {
                _preferences.SelectCharacter(slot);
                OnSetRandom?.Invoke(false);
                Close();
            };
        }
    }

    /// <summary>
    /// Whether this player already asked to spawn as a randomly generated character for this vote.
    /// </summary>
    private bool PrefersRandom()
    {
        return _entityManager.TryGetComponent<MoffEnrollEventComponent>(_enroller, out var comp)
               && _entityManager.GetNetEntity(_player.LocalEntity) is { } netEntity
               && comp.RandomPick.Contains(netEntity);
    }
}
