- type: entity
  name: starfruit
  parent: FoodProduceBase
  id: FoodStarfruit
  description: An exotic and strangely-shaped fruit.
  components:
  - type: FlavorProfile
    flavors:
    - sweet
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 9
        reagents:
        - ReagentId: Nutriment
          Quantity: 5
        - ReagentId: Vitamin
          Quantity: 4
  - type: Sprite
    sprite: _Moffstation/Objects/Specific/Hydroponics/starfruit.rsi
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: starfruit
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: JuiceStarfruit
        Quantity: 10
  - type: Tag
    tags:
    - Fruit
  - type: FoodSequenceElement
    entries:
      Burger: Starfruit
      Taco: Starfruit

- type: entity
  parent: ProduceBase
  id: FoodTarfruitWrapped
  name: tarfruit
  description: An odd starfruit that appears to be made of meat. It is wrapped in its outer... ears?
  components:
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 19
        reagents:
        - ReagentId: UncookedAnimalProteins
          Quantity: 9
        - ReagentId: Fat
          Quantity: 9
  - type: Sprite
    sprite: _Moffstation/Objects/Specific/Hydroponics/tarfruit.rsi
    state: produce
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: tarfruit
  - type: Tag
    tags:
    - Meat
    - Fruit
  - type: FoodSequenceElement
    entries:
      Burger: Tarfruit
      Taco: Tarfruit
  - type: SpawnItemsOnUse
    items:
    - id: TarfruitUnwrapped
    sound:
      path: /Audio/Effects/unwrap.ogg
