using System.Linq;
using Content.Shared._Moffstation.Silicons.StationAi;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.Silicons.StationAi;

[GenerateTypedNameReferences]
public sealed partial class AiShellSelectionMenu : DefaultWindow
{
    public Action<EntityUid>? JumpToShell;
    public Action<EntityUid>? EnterShell;
    public Action<EntityUid?>? SelectShell;

    [Dependency] private EntityManager _ent = null!;

    public AiShellSelectionMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        JumpToShellButton.OnPressed += OnJumpToShell;
        SelectShellButton.OnPressed += OnSelectShell;
    }

    private void OnSelectShell(BaseButton.ButtonEventArgs _)
    {
        if (Selected is not { } s)
            return;

        EnterShell?.Invoke(s);
    }

    private void OnJumpToShell(BaseButton.ButtonEventArgs _)
    {
        if (Selected is not { } s)
            return;

        JumpToShell?.Invoke(s);
    }

    public void Populate(AiShellControllerBuiState state)
    {
        ShellsList.Clear();

        foreach (var netShell in state.SelectableShells)
        {
            var shell = _ent.GetEntity(netShell);
            var item = ShellsList.AddItem(
                _ent.MetaQuery.GetComponent(shell).EntityName,
                metadata: shell
            );

            item.OnSelected += args =>
            {
                JumpToShellButton.Disabled = false;
                SelectShellButton.Disabled = false;
                SelectShell?.Invoke(args.Metadata is EntityUid ent ? ent : null);
            };

            item.OnDeselected += _ =>
            {
                JumpToShellButton.Disabled = true;
                SelectShellButton.Disabled = true;
            };

            // Select the AI's currently targeted shell inside the UI if possible
            if (state.SelectedShell == netShell)
            {
                item.Selected = true;
            }
        }
    }

    private EntityUid? Selected => ShellsList.GetSelected().FirstOrDefault()?.Metadata is EntityUid ret ? ret : null;
}
